'use strict';
const express=require('express');const crypto=require('crypto');const bcrypt=require('bcryptjs');const {z}=require('zod');const rateLimit=require('express-rate-limit');
const db=require('../config/db');const {asyncWrap,must,id}=require('../utils/http');const {teacher}=require('../middleware/auth');const {assertAssignedClass}=require('../services/permissions');const {audit}=require('../services/audit');
const sessions=require('../services/accountSessions');const accounts=require('../services/studentAccounts');const {progressShape,saveProgress}=require('../services/learningProgress');const {sendResetEmail}=require('../services/resetEmail');
const router=express.Router();
const loginLimit=rateLimit({windowMs:15*60000,limit:60,standardHeaders:'draft-7',legacyHeaders:false,message:{error:'Sign in is temporarily unavailable. Try again in 15 minutes or ask your teacher.'}});
const writeLimit=rateLimit({windowMs:60000,limit:60,standardHeaders:'draft-7',legacyHeaders:false});
router.use((req,res,next)=>{res.set('Cache-Control','no-store');next();});
router.get('/session',sessions.accountOptional,asyncWrap(async(req,res)=>{const a=req.accountSession;if(!a)return res.json({student:null,teacher:null});const student=a.student_id?(await db.query('SELECT * FROM students WHERE id=$1',[a.student_id])).rows[0]:null;const teacher=a.teacher_id?(await db.query('SELECT id,name,email,role,subject,assigned_classes FROM teachers WHERE id=$1',[a.teacher_id])).rows[0]:null;await db.query("UPDATE account_sessions SET last_seen_at=now() WHERE id=$1 AND last_seen_at<now()-interval '5 minutes'",[a.id]);res.json({student:student?accounts.publicStudent(student):null,teacher,csrfToken:a.csrfToken,expiresAt:a.expires_at});}));
router.post('/student/login',loginLimit,asyncWrap(async(req,res)=>{
 sessions.checkOrigin(req);const d=z.object({username:z.string().trim().min(1).max(40),password:z.string().min(1).max(128),remember:z.boolean().default(false)}).parse(req.body);
 const keys=accounts.loginKeys(req,'student',d.username),blocked=await accounts.locked(keys);
 const q=await db.query('SELECT * FROM students WHERE admission_number=$1 AND active=true',[d.username]);const s=q.rows[0];
 const ok=await bcrypt.compare(d.password,s?.password_hash||accounts.DUMMY);
 if(blocked||!s||!ok||(s.must_change_password&&new Date(s.temporary_password_expires_at).getTime()<Date.now())){await accounts.failure(keys);must(false,401,'Username or password is incorrect, or sign in is temporarily locked. Try again in 15 minutes or ask your teacher to reset your password.');}
 await accounts.success(keys);const result=await sessions.createSession(req,res,{studentId:s.id,remember:d.remember});res.json({student:accounts.publicStudent(s),...result});
}));
router.post('/logout',sessions.accountOptional,asyncWrap(async(req,res)=>{if(req.accountSession){sessions.checkCsrf(req,req.accountSession);await db.query('UPDATE account_sessions SET revoked_at=now() WHERE id=$1',[req.accountSession.id]);sessions.disconnectSessions([req.accountSession.id]);}else sessions.checkOrigin(req);sessions.clearCookie(res);res.json({signedOut:true});}));
router.post('/student/set-password',writeLimit,sessions.studentAccount(true),asyncWrap(async(req,res)=>{
 const d=z.object({newPassword:accounts.password,currentPassword:z.string().min(1).max(128).optional()}).strict().parse(req.body),s=req.studentAccount;
 if(!s.must_change_password){must(d.currentPassword&&await bcrypt.compare(d.currentPassword,s.password_hash),403,'Current password is incorrect.');}
 must(!(await bcrypt.compare(d.newPassword,s.password_hash)),400,'Choose a different password.');const passwordHash=await bcrypt.hash(d.newPassword,12);
 await db.transaction(async c=>{const q=await c.query('UPDATE students SET password_hash=$2,must_change_password=false,temporary_password_expires_at=NULL,updated_at=now() WHERE id=$1 AND password_hash=$3 RETURNING id',[s.id,passwordHash,s.password_hash]);must(q.rowCount,409,'Password was changed. Sign in again.');await c.query('UPDATE account_sessions SET revoked_at=now() WHERE student_id=$1 AND id<>$2',[s.id,req.accountSession.id]);await c.query('UPDATE student_password_resets SET used_at=now() WHERE student_id=$1 AND used_at IS NULL',[s.id]);});
 const q=await db.query('SELECT * FROM students WHERE id=$1',[s.id]);res.json({student:accounts.publicStudent(q.rows[0]),changed:true});
}));
router.post('/student/forgot-password',loginLimit,asyncWrap(async(req,res)=>{
 sessions.checkOrigin(req);const parsed=z.object({username:z.string().trim().min(1).max(40)}).safeParse(req.body);
 if(parsed.success){const q=await db.query('SELECT id,school_email FROM students WHERE admission_number=$1 AND active=true',[parsed.data.username]);const s=q.rows[0];if(s?.school_email){const token=crypto.randomBytes(32).toString('base64url');await db.query('INSERT INTO student_password_resets(student_id,token_hash,expires_at) VALUES($1,$2,now()+interval \'30 minutes\')',[s.id,sessions.digest(token)]);try{await sendResetEmail(s.school_email,token);}catch{console.error('[account email] Reset delivery failed.');}}}
 res.status(202).json({message:'If a school email is on file, a reset link can be sent there. You can always ask your teacher to reset your password.'});
}));
router.post('/student/reset-password',loginLimit,asyncWrap(async(req,res)=>{
 sessions.checkOrigin(req);const d=z.object({token:z.string().regex(/^[A-Za-z0-9_-]{43}$/),newPassword:accounts.password}).parse(req.body);const passwordHash=await bcrypt.hash(d.newPassword,12);
 await db.transaction(async c=>{const q=await c.query('SELECT r.id,r.student_id FROM student_password_resets r JOIN students s ON s.id=r.student_id AND s.active=true WHERE token_hash=$1 AND used_at IS NULL AND expires_at>now() FOR UPDATE OF r',[sessions.digest(d.token)]);must(q.rowCount,400,'This reset link has expired or was already used. Ask your teacher to reset your password.');const s=q.rows[0];await c.query('UPDATE students SET password_hash=$2,must_change_password=false,temporary_password_expires_at=NULL,updated_at=now() WHERE id=$1',[s.student_id,passwordHash]);await c.query('UPDATE student_password_resets SET used_at=now() WHERE student_id=$1 AND used_at IS NULL',[s.student_id]);await c.query('UPDATE account_sessions SET revoked_at=now() WHERE student_id=$1',[s.student_id]);});sessions.clearCookie(res);res.json({changed:true});
}));
router.get('/student/profile',sessions.studentAccount(),asyncWrap(async(req,res)=>{const s=req.studentAccount;const q=await db.query('SELECT progress,updated_at FROM student_learning_progress WHERE student_id=$1',[s.id]);const deletion=await db.query("SELECT status,requested_at FROM student_deletion_requests WHERE student_id=$1 ORDER BY requested_at DESC LIMIT 1",[s.id]);res.json({student:accounts.publicStudent(s),history:await accounts.examHistory(s.id),learning:q.rows[0]?.progress||{courses:{},games:{},mocks:[],customTests:[]},deletionRequest:deletion.rows[0]||null});}));
router.put('/student/profile',writeLimit,sessions.studentAccount(),asyncWrap(async(req,res)=>{const d=z.object({displayName:z.string().trim().max(40),avatar:z.enum(accounts.avatars),theme:z.enum(['light','dark','system'])}).strict().parse(req.body);const q=await db.query('UPDATE students SET display_name=$2,avatar=$3,theme=$4,updated_at=now() WHERE id=$1 RETURNING *',[req.studentAccount.id,d.displayName,d.avatar,d.theme]);res.json({student:accounts.publicStudent(q.rows[0])});}));
router.get('/student/submissions/:id',sessions.studentAccount(),asyncWrap(async(req,res)=>{must(id(req.params.id),404,'Submission not found.');const q=await db.query(`SELECT s.id,e.title,e.results_released_at FROM exam_sessions s JOIN exams e ON e.id=s.exam_id WHERE s.id=$1 AND s.student_id=$2 AND s.status='submitted' AND e.results_released_at IS NOT NULL`,[req.params.id,req.studentAccount.id]);must(q.rowCount,404,'Submission not found.');const answers=await db.query('SELECT a.question_id,q.title,q.type,q.marks,a.answer_text,a.code,a.language,a.marks_awarded,a.teacher_remarks AS remarks FROM answers a JOIN questions q ON q.id=a.question_id WHERE a.session_id=$1 ORDER BY q.sort_order',[req.params.id]);res.json({submission:q.rows[0],answers:answers.rows});}));
router.get('/student/sessions',sessions.studentAccount(),asyncWrap(async(req,res)=>{const q=await db.query('SELECT id,device_label,created_at,last_seen_at,expires_at FROM account_sessions WHERE student_id=$1 AND revoked_at IS NULL AND expires_at>now() ORDER BY created_at DESC',[req.studentAccount.id]);res.json({sessions:q.rows.map(x=>({...x,current:x.id===req.accountSession.id}))});}));
router.post('/student/sessions/revoke-others',sessions.studentAccount(),asyncWrap(async(req,res)=>{await sessions.revokeSessions({studentId:req.studentAccount.id,except:req.accountSession.id});res.json({signedOut:true});}));
router.get('/student/learning',sessions.studentAccount(),asyncWrap(async(req,res)=>{const q=await db.query('SELECT progress,updated_at FROM student_learning_progress WHERE student_id=$1',[req.studentAccount.id]);res.json({progress:q.rows[0]?.progress||{courses:{},games:{},mocks:[],customTests:[]},updatedAt:q.rows[0]?.updated_at||null});}));
router.put('/student/learning',writeLimit,sessions.studentAccount(),asyncWrap(async(req,res)=>res.json({progress:await saveProgress(req.studentAccount.id,progressShape.parse(req.body))})));
router.post('/student/learning/import',writeLimit,sessions.studentAccount(),asyncWrap(async(req,res)=>{const d=z.object({consent:z.boolean(),progress:progressShape.optional(),practiceToken:z.string().max(1000).optional()}).strict().parse(req.body);must(!req.studentAccount.learning_import_decided_at,409,'A choice was already saved.');
 if(d.consent&&d.progress)await saveProgress(req.studentAccount.id,d.progress);
 if(d.consent&&d.practiceToken){let t;try{t=require('jsonwebtoken').verify(d.practiceToken,require('../config/env').env.JWT_SECRET,{issuer:'dps-practice'});}catch{}if(t?.kind==='practice')await db.transaction(async c=>{const old=await c.query('SELECT id FROM practice_users WHERE id=$1 AND student_id IS NULL AND active=true FOR UPDATE',[t.sub]);if(old.rowCount){const existing=await c.query('SELECT id FROM practice_users WHERE student_id=$1',[req.studentAccount.id]);if(!existing.rowCount){await c.query('UPDATE practice_users SET student_id=$2,password_hash=$3 WHERE id=$1',[t.sub,req.studentAccount.id,'!school-account-only']);for(const table of ['course_enrollments','course_attempts','practice_game_results'])await c.query(`UPDATE ${table} SET student_id=$2 WHERE user_id=$1`,[t.sub,req.studentAccount.id]);}else{await c.query('INSERT INTO course_enrollments(user_id,course_id,completed_lessons) SELECT $2,course_id,completed_lessons FROM course_enrollments WHERE user_id=$1 ON CONFLICT(user_id,course_id) DO UPDATE SET completed_lessons=(SELECT jsonb_agg(DISTINCT v) FROM jsonb_array_elements(course_enrollments.completed_lessons||excluded.completed_lessons) AS x(v))',[t.sub,existing.rows[0].id]);await c.query('UPDATE course_attempts SET user_id=$2 WHERE user_id=$1',[t.sub,existing.rows[0].id]);await c.query('UPDATE practice_game_results SET user_id=$2 WHERE user_id=$1',[t.sub,existing.rows[0].id]);await c.query('UPDATE practice_users SET active=false,password_hash=$2 WHERE id=$1',[t.sub,'!imported-school-account']);}}});}
 await db.query('UPDATE students SET learning_import_decided_at=now() WHERE id=$1',[req.studentAccount.id]);res.json({imported:d.consent});
}));
router.get('/student/data',sessions.studentAccount(),asyncWrap(async(req,res)=>{const s=req.studentAccount;const progress=await db.query('SELECT progress FROM student_learning_progress WHERE student_id=$1',[s.id]);const attempts=await db.query('SELECT id,exam_id,student_name,roll_number,class_name,section,joined_at,submitted_at,status FROM exam_sessions WHERE student_id=$1',[s.id]);const answers=await db.query('SELECT a.session_id,a.question_id,a.answer_text,a.code,a.language,a.submitted_at,CASE WHEN e.results_released_at IS NOT NULL THEN a.marks_awarded END AS marks_awarded FROM answers a JOIN exams e ON e.id=a.exam_id WHERE a.student_id=$1',[s.id]);const events=await db.query('SELECT exam_id,session_id,event_type AS type,severity,message,created_at FROM anti_cheat_events WHERE student_id=$1',[s.id]);const courses=await db.query('SELECT course_id,completed_lessons,joined_at FROM course_enrollments WHERE student_id=$1',[s.id]);const quizzes=await db.query('SELECT course_id,score,correct,total,submitted_at FROM course_attempts WHERE student_id=$1',[s.id]);const games=await db.query('SELECT game_id,score,created_at FROM practice_game_results WHERE student_id=$1',[s.id]);res.set('Content-Disposition','attachment; filename="my-dps-data.json"');res.json({exportedAt:new Date().toISOString(),profile:accounts.publicStudent(s),examAttempts:attempts.rows,answers:answers.rows,proctorEvents:events.rows,learning:progress.rows[0]?.progress||{},courses:courses.rows,courseAttempts:quizzes.rows,gameScores:games.rows});}));
router.post('/student/deletion-request',sessions.studentAccount(),asyncWrap(async(req,res)=>{await db.query("INSERT INTO student_deletion_requests(student_id) VALUES($1) ON CONFLICT(student_id) WHERE status='pending' DO NOTHING",[req.studentAccount.id]);res.status(202).json({requested:true,message:'Your teacher will review this request. Exam records are preserved.'});}));

// Every roster operation checks the teacher's assignment; IDs alone confer no access.
async function ownedStudent(req){must(id(req.params.id),404,'Student not found.');const q=await db.query('SELECT * FROM students WHERE id=$1',[req.params.id]);must(q.rowCount,404,'Student not found.');await assertAssignedClass(req.teacher,q.rows[0].class_name,q.rows[0].section);return q.rows[0];}
router.get('/teacher/students',teacher,asyncWrap(async(req,res)=>{const cls=z.string().min(1).max(40).parse(req.query.className);await assertAssignedClass(req.teacher,cls);const q=await db.query(`SELECT s.*,d.id AS deletion_request_id,d.requested_at AS deletion_requested_at FROM students s LEFT JOIN student_deletion_requests d ON d.student_id=s.id AND d.status='pending' WHERE lower(s.class_name)=lower($1) ORDER BY s.section,s.roll_number LIMIT 1500`,[cls]);res.json({students:q.rows.map(s=>({...accounts.publicStudent(s),deletionRequestId:s.deletion_request_id,deletionRequestedAt:s.deletion_requested_at}))});}));
router.post('/teacher/students',teacher,writeLimit,asyncWrap(async(req,res)=>{const d=accounts.studentFields.parse(req.body);await assertAssignedClass(req.teacher,d.className,d.section);const result=await db.transaction(c=>accounts.addStudent(c,d,req.teacher.id));await audit({teacherId:req.teacher.id,action:'student:create',details:{studentId:result.student.id}});res.status(201).json(result);}));
router.post('/teacher/students/import',teacher,writeLimit,asyncWrap(async(req,res)=>{const d=z.object({className:z.string().min(1).max(40),csv:z.string().max(80000),dryRun:z.boolean().default(true)}).strict().parse(req.body);await assertAssignedClass(req.teacher,d.className);const rows=accounts.parseCsv(d.csv),errors=[],valid=[],usernames=new Set(),rolls=new Set();const existing=await db.query('SELECT admission_number,roll_number,class_name,section,active FROM students');const allUsers=new Set(existing.rows.map(s=>s.admission_number.toLowerCase()));const allRolls=new Set(existing.rows.filter(s=>s.active).map(s=>[s.roll_number,s.class_name,s.section].join('|').toLowerCase()));
 for(const row of rows){const parsed=accounts.studentFields.safeParse(row.data);if(row.error||!parsed.success){errors.push({line:row.line,error:row.error||parsed.error.issues.map(x=>x.path+': '+x.message).join('; ')});continue;}const s=parsed.data,username=s.admissionNumber.toLowerCase(),roll=[s.rollNumber,s.className,s.section].join('|').toLowerCase();if(s.className.toLowerCase()!==d.className.toLowerCase()){errors.push({line:row.line,error:'Class does not match the selected class.'});continue;}try{await assertAssignedClass(req.teacher,s.className,s.section);}catch(e){errors.push({line:row.line,error:e.message});continue;}if(usernames.has(username)||allUsers.has(username)||rolls.has(roll)||allRolls.has(roll)){errors.push({line:row.line,error:'Duplicate admission number or active roll number in this class and section.'});continue;}usernames.add(username);rolls.add(roll);valid.push({line:row.line,data:s});}
 if(d.dryRun||errors.length)return res.status(errors.length&&!d.dryRun?400:200).json({dryRun:true,validRows:valid.length,errors,created:[]});
 const created=await db.transaction(async c=>{const out=[];for(const r of valid)out.push(await accounts.addStudent(c,r.data,req.teacher.id));return out;});await audit({teacherId:req.teacher.id,action:'student:csv-import',details:{className:d.className,count:created.length}});res.status(201).json({dryRun:false,validRows:created.length,errors:[],created});
}));
router.get('/teacher/students/:id',teacher,asyncWrap(async(req,res)=>{const s=await ownedStudent(req);const deletion=await db.query("SELECT id,status,requested_at FROM student_deletion_requests WHERE student_id=$1 ORDER BY requested_at DESC LIMIT 1",[s.id]);res.json({student:accounts.publicStudent(s),history:await accounts.examHistory(s.id,false),deletionRequest:deletion.rows[0]||null});}));
router.put('/teacher/students/:id',teacher,writeLimit,asyncWrap(async(req,res)=>{const old=await ownedStudent(req);const d=accounts.studentFields.omit({admissionNumber:true}).extend({active:z.boolean()}).parse(req.body);await assertAssignedClass(req.teacher,d.className,d.section);const q=await db.query('UPDATE students SET name=$2,roll_number=$3,class_name=$4,section=$5,school_email=$6,active=$7,updated_at=now() WHERE id=$1 RETURNING *',[old.id,d.name,d.rollNumber,d.className,d.section,d.schoolEmail||null,d.active]);await sessions.revokeSessions({studentId:old.id});await audit({teacherId:req.teacher.id,action:'student:edited',details:{studentId:old.id}});res.json({student:accounts.publicStudent(q.rows[0])});}));
router.post('/teacher/students/:id/reset-password',teacher,writeLimit,asyncWrap(async(req,res)=>{const s=await ownedStudent(req);must(s.active,409,'Activate this student before resetting their password.');const raw=accounts.temporaryPassword(),passwordHash=await bcrypt.hash(raw,12);await db.transaction(async c=>{await c.query('UPDATE students SET password_hash=$2,must_change_password=true,temporary_password_expires_at=now()+interval \'7 days\',updated_at=now() WHERE id=$1',[s.id,passwordHash]);await c.query('UPDATE account_sessions SET revoked_at=now() WHERE student_id=$1',[s.id]);await c.query('UPDATE student_password_resets SET used_at=now() WHERE student_id=$1 AND used_at IS NULL',[s.id]);});await audit({teacherId:req.teacher.id,action:'student:password-reset',details:{studentId:s.id}});res.json({student:accounts.publicStudent({...s,must_change_password:true}),temporaryPassword:raw});}));
router.post('/teacher/students/:id/deletion-request',teacher,asyncWrap(async(req,res)=>{const s=await ownedStudent(req);const d=z.object({decision:z.enum(['approved','declined'])}).parse(req.body);const q=await db.query("UPDATE student_deletion_requests SET status=$2,resolved_at=now(),resolved_by=$3 WHERE student_id=$1 AND status='pending' RETURNING id",[s.id,d.decision,req.teacher.id]);must(q.rowCount,404,'No pending request.');if(d.decision==='approved'){await db.query('UPDATE students SET active=false,school_email=NULL,display_name=\'\',updated_at=now() WHERE id=$1',[s.id]);await sessions.revokeSessions({studentId:s.id});}await audit({teacherId:req.teacher.id,action:'student:deletion-reviewed',details:{studentId:s.id,decision:d.decision}});res.json({resolved:true,recordsPreserved:true});}));
module.exports=router;
