import * as m from 'motion/react-m'
import { useQuietMotion } from '../common/Motion'
import { Spinner,ErrorNote } from '../common/Feedback'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Plus, Printer, Upload, Users } from 'lucide-react'
import { accountApi } from '../../services/accountApi'
const fields=[['admissionNumber','Admission number (username)'],['name','Full name'],['rollNumber','Roll number'],['section','Section'],['schoolEmail','School email (optional)']]
export function CredentialSlips({ credentials, clear }) {
 function print(){document.body.classList.add('print-credentials');window.addEventListener('afterprint',()=>document.body.classList.remove('print-credentials'),{once:true});window.print()}
 return credentials.length>0&&<><div className="credential-preview mt-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">One-time credentials · {credentials.length} slip{credentials.length===1?'':'s'}</h3><div className="flex gap-2"><button className="btn btn-primary btn-sm" onClick={print}><Printer size={14}/> Print slips</button><button className="btn btn-ghost btn-sm" onClick={clear}>Clear credentials</button></div></div><p className="mt-2 text-sm text-slate-400">Print and hand out privately. Passwords disappear when you leave this page. Students must change them at first sign in; slips expire after 7 days.</p>{credentials.map(c=><p className="mt-3 text-sm" key={c.student.id}>{c.student.name} · <code>{c.student.username}</code> · <code>{c.temporaryPassword}</code></p>)}</div><div className="credential-slips">{credentials.map(c=><article className="credential-slip" key={c.student.id}><h3>DPS Agra · Student sign in</h3><p>{c.student.name} · Class {c.student.className}-{c.student.section} · Roll {c.student.rollNumber}</p><p>Username: <code>{c.student.username}</code><br/>Temporary password: <code>{c.temporaryPassword}</code></p><p>Open dpslab.onrender.com/#/student/login<br/>Set a new password the first time you sign in.<br/>Keep this slip private. Valid for 7 days.</p></article>)}</div></>
}
export default function StudentRoster({ className, sections=[] }){
 const quiet=useQuietMotion(),[loading,setLoading]=useState(true)
 const [students,setStudents]=useState([]),[form,setForm]=useState({admissionNumber:'',name:'',rollNumber:'',section:sections[0]||'A',schoolEmail:''}),[mode,setMode]=useState(''),[csv,setCsv]=useState(''),[report,setReport]=useState(null),[credentials,setCredentials]=useState([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState(null)
 const load=()=>{setLoading(true);return accountApi('/teacher/students?className='+encodeURIComponent(className)).then(r=>setStudents(r.students)).finally(()=>setLoading(false))}
 useEffect(()=>{setCredentials([]);setReport(null);setMode('');setError('');load().catch(e=>setError(e.message));setForm({admissionNumber:'',name:'',rollNumber:'',section:sections[0]||'A',schoolEmail:''})},[className])
 async function act(fn){setBusy(true);setError('');setMessage('');try{await fn();await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function add(e){e.preventDefault();await act(async()=>{const r=await accountApi('/teacher/students',{method:'POST',body:{...form,className}});setCredentials(c=>[...c,r]);setMode('');setForm({...form,admissionNumber:'',name:'',rollNumber:'',schoolEmail:''});setMessage('Student added. Print their sign-in slip.')})}
 async function importCsv(dryRun){await act(async()=>{const r=await accountApi('/teacher/students/import',{method:'POST',body:{className,csv,dryRun}});setReport(r);if(!dryRun){setCredentials(c=>[...c,...r.created]);setMode('');setCsv('');setMessage(`${r.created.length} students added.`)}})}
 function editStudent(s){setEdit(s);setMode('edit')}
 async function saveEdit(e){e.preventDefault();await act(async()=>{await accountApi('/teacher/students/'+edit.id,{method:'PUT',body:{name:edit.name,rollNumber:edit.rollNumber,className:edit.className,section:edit.section,schoolEmail:edit.schoolEmail,active:edit.active}});setMode('');setEdit(null);setMessage('School details updated. The student will sign in again.')})}
 return <section className="roster-panel glass mb-6 p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="flex items-center gap-2 text-xl font-semibold"><Users size={21}/> Student accounts · Class {className}</h2><p className="mt-1 text-sm text-slate-400">{students.filter(s=>s.active).length} active · Accounts are issued by teachers.</p></div><div className="flex gap-2"><button className="btn btn-primary btn-sm" onClick={()=>setMode(mode==='add'?'':'add')}><Plus size={15}/> Add student</button><button className="btn btn-ghost btn-sm" onClick={()=>{setMode(mode==='csv'?'':'csv');setReport(null)}}><Upload size={15}/> Import CSV</button></div></div>{error&&<div className="mt-4"><ErrorNote message={error} onRetry={()=>load().then(()=>setError('')).catch(e=>setError(e.message))}/></div>}{message&&<p className="mt-3 text-sm" role="status">{message}</p>}
 {mode==='add'&&<form className="mt-5 grid gap-4 rounded-xl border border-white/10 p-4 sm:grid-cols-2" onSubmit={add}>{fields.map(([key,label])=><label key={key} className="block text-sm">{label}{key==='section'?<select className="input mt-2" value={form.section} onChange={e=>setForm({...form,section:e.target.value})}>{sections.map(s=><option key={s}>{s}</option>)}</select>:<input className="input mt-2" type={key==='schoolEmail'?'email':'text'} maxLength={key==='name'?120:key==='schoolEmail'?200:40} required={key!=='schoolEmail'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}<div className="flex items-end gap-2"><button className="btn btn-primary" disabled={busy}>Create account</button><button className="btn btn-ghost" type="button" onClick={()=>setMode('')}>Cancel</button></div></form>}
 {mode==='csv'&&<div className="mt-5 space-y-4 rounded-xl border border-white/10 p-4"><p className="text-sm text-slate-400">Use headers: admission number, name, roll number, class, section, school email. Admission numbers are required as usernames. Import up to 300 students. Fix all bad rows before importing.</p><label className="block text-sm">Choose CSV file<input type="file" accept=".csv,text/csv" className="input mt-2" onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>80000){setError('CSV must be at most 80 KB.');return}setCsv(await f.text());setReport(null)}}}/></label><label className="block text-sm">CSV content<textarea className="input mt-2 font-mono text-xs" rows={6} value={csv} onChange={e=>{setCsv(e.target.value);setReport(null)}} placeholder={'admission number,name,roll number,class,section,school email\nAGR1001,Student Name,1,'+className+',A,'}/></label><div className="flex gap-2"><button className="btn btn-ghost" disabled={busy||!csv} onClick={()=>importCsv(true)}>Check rows</button><button className="btn btn-primary" disabled={busy||!report||report.errors.length>0||!report.validRows} onClick={()=>importCsv(false)}>Import checked students</button></div>{report&&<div role="status"><p className="text-sm">{report.validRows} valid row{report.validRows===1?'':'s'}. {report.errors.length} error{report.errors.length===1?'':'s'}.</p><ul className="mt-2 space-y-1 text-sm">{report.errors.map(e=><li className="text-red-500" key={e.line}>Row {e.line}: {e.error}</li>)}</ul></div>}</div>}
 {mode==='edit'&&edit&&<form className="mt-5 grid gap-4 rounded-xl border border-white/10 p-4 sm:grid-cols-2" onSubmit={saveEdit}><h3 className="font-semibold sm:col-span-2">Edit {edit.username}</h3>{[['name','Full name'],['rollNumber','Roll number'],['className','Class'],['section','Section'],['schoolEmail','School email (optional)']].map(([key,label])=><label className="block text-sm" key={key}>{label}<input className="input mt-2" value={edit[key]} required={key!=='schoolEmail'} type={key==='schoolEmail'?'email':'text'} onChange={e=>setEdit({...edit,[key]:e.target.value})}/></label>)}<label className="flex items-center gap-2"><input type="checkbox" checked={edit.active} onChange={e=>setEdit({...edit,active:e.target.checked})}/> Account active</label><div className="flex gap-2 sm:col-span-2"><button className="btn btn-primary" disabled={busy}>Save details</button><button className="btn btn-ghost" type="button" onClick={()=>setMode('')}>Cancel</button></div></form>}
 <CredentialSlips credentials={credentials} clear={()=>setCredentials([])}/>{loading && <Spinner label="Loading the class roster…"/>}<div className="mt-5 overflow-x-auto" role="region" aria-label="Student account roster" tabIndex={0}><table className="table-base roster-table"><thead><tr><th>Roll / Section</th><th>Student</th><th>Username</th><th>Status</th><th>Actions</th></tr></thead><tbody>{students.map(s=><m.tr key={s.id} initial={quiet?false:{opacity:0,y:4}} animate={{opacity:1,y:0}}><td>{s.rollNumber} · {s.section}</td><td><Link className="text-dps-green hover:underline" to={'/teacher/students/'+s.id}>{s.name}</Link>{s.deletionRequestId&&<p className="mt-1 text-xs text-red-500">Deletion request pending</p>}</td><td>{s.username}</td><td>{s.active?(s.mustChangePassword?'First sign in pending':'Active'):'Inactive'}</td><td><div className="roster-actions"><button className="btn btn-ghost btn-sm" onClick={()=>editStudent(s)}>Edit</button><button className="btn btn-ghost btn-sm" disabled={busy||!s.active} onClick={()=>act(async()=>{const r=await accountApi('/teacher/students/'+s.id+'/reset-password',{method:'POST'});setCredentials(c=>[...c.filter(x=>x.student.id!==s.id),r]);setMessage('New temporary password issued. Previous sessions were signed out.')})}>Reset password</button><button className="btn btn-ghost btn-sm" disabled={busy} onClick={()=>act(async()=>{await accountApi('/teacher/students/'+s.id,{method:'PUT',body:{name:s.name,rollNumber:s.rollNumber,className:s.className,section:s.section,schoolEmail:s.schoolEmail,active:!s.active}});setMessage(s.active?'Account deactivated. Exam records preserved.':'Account activated.')})}>{s.active?'Deactivate':'Activate'}</button></div></td></m.tr>)}</tbody></table>{!loading&&!error&&!students.length&&<p className="py-5 text-sm text-slate-400">No accounts yet. Add a student or import your class list.</p>}</div></section>
}
