import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
const src=name=>readFileSync('src/'+name,'utf8')
test('camera stills reuse the explicit webcam consent and live stream from exam entry',()=>{
 const room=src('pages/ExamRoom.jsx')
 const indicator=src('components/proctoring/MonitoringIndicator.jsx')
 const hook=src('hooks/useSnapshots.js')
 const join=src('pages/StudentJoinPage.jsx')
 assert.match(room,/useStudentSnapshots\(socket,streams\.webcam,phase==='active'\)/)
 assert.match(join,/temporary compressed stills/)
 assert.doesNotMatch(indicator,/onSnapshotChange|Allow webcam snapshots/)
 assert.match(indicator,/Camera permission is active/)
 assert.match(hook,/const ready=active&&requested&&live&&socket\?\.connected/)
 assert.match(hook,/canvas\.toDataURL\('image\/jpeg',\.44\)/)
 assert.match(hook,/const EVERY_MS=4200/)
 assert.match(hook,/student:snapshotConsent/)
 assert.doesNotMatch(hook,/setAllowed/)
})
test('teacher automatically subscribes only to the selected student and never caches stills persistently',()=>{
 const hook=src('hooks/useTeacherSnapshots.js')
 const panel=src('components/proctoring/StudentDetailPanel.jsx')
 assert.match(hook,/teacher:snapshotSubscribe/)
 assert.match(hook,/teacher:snapshotUnsubscribe/)
 assert.match(hook,/teacher:snapshotKeepalive/)
 assert.match(hook,/setFrames\(\{\}\)/)
 assert.doesNotMatch(hook,/localStorage|sessionStorage|indexedDB/)
 assert.match(panel,/subscribeStills\(sessionId\)/)
 assert.match(panel,/stopStills\?\.\(sessionId\)/)
 assert.match(panel,/about every 4 seconds/)
 assert.doesNotMatch(panel,/Request webcam snapshots/)
})
