import test from 'node:test'
import assert from 'node:assert/strict'
import {formatSaveAge,checkInCountdown} from '../src/utils/ui.js'
import {compareAttention,attentionCounts} from '../src/utils/monitorAttention.js'
import {readFileSync} from 'node:fs'
test('save age handles seconds, minutes, missing timestamps and clock skew',()=>{const now=Date.UTC(2026,9,2);assert.equal(formatSaveAge(now-5000,now),'Saved 5s ago');assert.equal(formatSaveAge(now-120000,now),'Saved 2 min ago');assert.equal(formatSaveAge(now+5000,now),'Saved just now');assert.equal(formatSaveAge(undefined,now),'All changes saved')})
test('check-in countdown uses exactly the existing 30-minute window',()=>{const start=Date.UTC(2026,9,2,12);assert.equal(checkInCountdown(start,start-31*60000),'Check-in opens in 1m 0s');assert.match(checkInCountdown(start,start-30*60000),/Check-in is open/);assert.match(checkInCountdown(start,start),/scheduled start time/);assert.match(checkInCountdown(undefined),/teacher/)})
test('monitor uses recorded severity before display fallbacks and prioritises attention',()=>{const rows=[{rollNumber:'1',flags:{},status:'active'},{rollNumber:'2',flags:{},connected:false},{rollNumber:'3',flags:{tab:1},timeline:[{type:'tab_hidden',severity:'medium'}]},{rollNumber:'4',flags:{other:1},timeline:[{type:'screen_share_stopped',severity:'high'}]}];assert.deepEqual([...rows].sort(compareAttention).map(x=>x.rollNumber),['4','3','2','1']);assert.deepEqual(attentionCounts(rows[2]),{high:0,medium:1,low:0});assert.deepEqual(rows.map(x=>x.rollNumber),['1','2','3','4'])})
test('fonts load once and ambient CSS keyframes have been removed',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.equal((html.match(/fonts.googleapis.com\/css2/g)||[]).length,1);assert.match(html,/display=swap/);const styles=['globals','animations','learning-remake','exam-portal','student-accounts'].map(name=>readFileSync(new URL(`../src/styles/${name}.css`,import.meta.url),'utf8')).join('\n');assert.ok(!/@import|Georgia|Manrope|Space Grotesk/.test(styles));const frames=[...styles.matchAll(/@keyframes ([\w-]+)/g)].map(m=>m[1]);assert.deepEqual(frames,['skeleton-shimmer','live-signal']);assert.match(styles,/prefers-reduced-motion:reduce/);assert.match(styles,/:focus-visible/)})
