import { useEffect, useState } from 'react'
import { ShieldCheck, UserPlus, UserX, Users } from 'lucide-react'
import { getTeacherAuth } from '../services/session'
import { http } from '../services/api'
import { learningApi } from '../services/learningApi'
const classes=['VI','VII','VIII','IX','X','XI','XII']
export default function ManageTeachers(){
 const auth=getTeacherAuth();const [teachers,setTeachers]=useState([]),[form,setForm]=useState({name:'',email:'',password:'',subject:'Computers',role:'teacher',assignedClasses:[]}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false)
 const reload=()=>learningApi('/teacher/admin/teachers',{teacher:true}).then(x=>setTeachers(x.teachers)).catch(e=>setError(e.message))
 useEffect(()=>{if(auth?.teacher?.role==='admin')reload()},[])
 if(auth?.teacher?.role!=='admin')return <p className="p-8 text-red-300">Authorized portal administrators only. Teacher accounts cannot be created by public visitors or students.</p>
 async function add(e){e.preventDefault();setError('');setNotice('');setSaving(true);try{await http.post('/api/auth/teacher/register',form,{headers:{Authorization:`Bearer ${auth.token}`}});setNotice('Teacher enrolled. Give their password securely and require them to change it through an administrator-approved process.');setForm({name:'',email:'',password:'',subject:'Computers',role:'teacher',assignedClasses:[]});reload()}catch(e){setError(e.response?.data?.error||e.message)}finally{setSaving(false)}}
 async function toggle(t){if(!window.confirm(`${t.active?'Deactivate':'Reactivate'} ${t.name}?`))return;try{await learningApi(`/teacher/admin/teachers/${t.id}`,{teacher:true,method:'PATCH',body:{active:!t.active}});reload()}catch(e){setError(e.message)}}
 return <div className="mx-auto max-w-6xl space-y-7"><span className="chip"><ShieldCheck size={14}/> Administrator access</span><h1 className="mt-2 text-3xl font-bold">Manage authorized teachers</h1><p className="text-slate-400">Only the portal administrator can create or disable real teacher accounts. Do not enroll staff or represent your school without its authorization.</p><div className="grid gap-6 lg:grid-cols-[1fr,1fr]"><form onSubmit={add} className="glass space-y-4 p-6"><h2 className="flex items-center gap-2 text-xl font-semibold"><UserPlus size={20}/> Enroll a teacher</h2><label className="block text-sm">Name<input className="input mt-1" required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="block text-sm">School-issued email<input type="email" className="input mt-1" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="block text-sm">Temporary password (12+ characters)<input type="password" autoComplete="new-password" className="input mt-1" minLength={12} maxLength={128} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label className="block text-sm">Subject<input className="input mt-1" value={form.subject} maxLength={90} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label className="block text-sm">Role<select className="input mt-1" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="teacher">Teacher</option><option value="admin">Administrator (full access)</option></select></label><fieldset><legend className="text-sm">Assigned classes</legend><div className="mt-3 flex flex-wrap gap-3">{classes.map(c=><label className="flex gap-1.5 text-sm" key={c}><input type="checkbox" checked={form.assignedClasses.includes(c)} onChange={e=>setForm(f=>({...f,assignedClasses:e.target.checked?[...f.assignedClasses,c]:f.assignedClasses.filter(x=>x!==c)}))}/>{c}</label>)}</div></fieldset>{notice&&<p className="text-dps-neon" role="status">{notice}</p>}{error&&<p className="text-red-300" role="alert">{error}</p>}<button className="btn btn-primary" disabled={saving}>{saving?'Creating...':'Create teacher account'}</button></form><section className="glass p-6"><h2 className="flex gap-2 text-xl font-semibold"><Users size={20}/> Enrolled staff</h2>{teachers.map(t=><div key={t.id} className="mt-4 flex items-center justify-between gap-3 rounded-xl border border-white/10 p-4"><div><b>{t.name}</b><p className="text-xs text-slate-400">{t.email} • {t.role}</p><p className="mt-1 text-xs text-slate-400">{t.assigned_classes?.join(', ')||'No assigned classes'}</p></div><button disabled={t.id===auth?.teacher?.id} type="button" className="btn btn-ghost btn-sm" onClick={()=>toggle(t)}>{t.active?<><UserX size={14}/> Disable</>:'Reactivate'}</button></div>)}</section></div></div>
}
