import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { AlarmClock, Award, ClipboardCheck, RotateCcw } from 'lucide-react'
import Navbar from '../components/layout/Navbar'
import Footer from '../components/layout/Footer'
import { MOCK_EXAM } from '../services/gameQuestions'
import { getLearningAuth, learningApi } from '../services/learningApi'
const DURATION=15*60
export default function MockExam(){
 const [started,setStarted]=useState(false),[remaining,setRemaining]=useState(DURATION),[answers,setAnswers]=useState({}),[finished,setFinished]=useState(false),[saved,setSaved]=useState(''),[showReview,setShowReview]=useState(false)
 useEffect(()=>{if(!started||finished)return;const timer=setInterval(()=>setRemaining(x=>{if(x<=1){setFinished(true);return 0}return x-1}),1000);return()=>clearInterval(timer)},[started,finished])
 const correct=MOCK_EXAM.filter((q,i)=>answers[i]===q.correct).length,percent=Math.round(correct/MOCK_EXAM.length*100)
 useEffect(()=>{if(!finished)return;const result={at:new Date().toISOString(),score:percent,correct,total:MOCK_EXAM.length};try{let previous=JSON.parse(localStorage.getItem('dps.mock.history')||'[]');localStorage.setItem('dps.mock.history',JSON.stringify([result,...previous].slice(0,20)))}catch{}if(getLearningAuth())learningApi('/games',{method:'POST',body:{gameId:'mock-practical',score:percent}}).then(()=>setSaved('Saved to your practice profile.')).catch(()=>{})},[finished])
 return <div className="flex min-h-screen flex-col"><Navbar/><main className="mx-auto w-full max-w-4xl flex-1 px-4 py-10 sm:px-6"><span className="chip"><ClipboardCheck size={14}/> Class IX mock assessment</span><h1 className="mt-4 text-3xl font-bold">A proper exam feel. <span className="text-gradient">Zero pressure.</span></h1><p className="mt-3 text-slate-400">A self-paced 15-minute, 12-question mock test covering Python, HTML, SQL and computing fundamentals. No webcam, roll number or school registration. Results are for practice only.</p>
 {!started?<section className="glass mt-8 p-8"><h2 className="text-2xl font-semibold">Ready to begin?</h2><ul className="mt-4 space-y-2 text-slate-300"><li>• 12 multiple choice questions, one mark each</li><li>• 15 minute countdown and automatic finish</li><li>• Full explanations available after the test</li><li>• Scores remain on your device and optionally your nickname profile</li></ul><button className="btn btn-primary mt-6" onClick={()=>{setStarted(true);setRemaining(DURATION);setAnswers({});setFinished(false);setShowReview(false)}}>Start practice test</button></section>:<div className="mt-8"><div className="glass sticky top-16 z-10 mb-5 flex flex-wrap items-center justify-between gap-3 p-4"><p className="font-semibold">Answered {Object.keys(answers).length} / {MOCK_EXAM.length}</p><span className={`chip ${remaining<120?'border-red-400 text-red-300':'text-dps-neon'}`}><AlarmClock size={14}/> {Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')} remaining</span></div>{finished?<section className="glass p-8 text-center"><Award size={42} className="mx-auto text-dps-gold"/><p className="mt-3 text-5xl font-bold text-dps-neon">{percent}%</p><p className="mt-2">{correct}/{MOCK_EXAM.length} correct. {saved}</p><p className="mt-3 text-sm text-slate-400">Unofficial practice report only; no official grades or proctoring here.</p><div className="mt-6 flex justify-center gap-3"><button className="btn btn-primary" onClick={()=>setShowReview(x=>!x)}>{showReview?'Hide explanations':'Review answers'}</button><button className="btn btn-ghost" onClick={()=>{setStarted(false);setFinished(false);setRemaining(DURATION);setAnswers({})}}><RotateCcw size={16}/> Retake</button></div>{showReview&&<div className="mt-8 space-y-4 text-left">{MOCK_EXAM.map((q,i)=><div key={i} className="rounded-xl border border-white/10 p-4"><b>{i+1}. {q.prompt}</b><p className="mt-2 text-sm text-slate-400">Your answer: {answers[i]==null?'Not answered':q.options[answers[i]]} {answers[i]===q.correct?'✓':'✗'}</p><p className="mt-1 text-sm text-dps-neon">Answer: {q.options[q.correct]}</p><p className="mt-1 text-sm text-slate-300">{q.explanation}</p></div>)}</div>}</section>:<form onSubmit={e=>{e.preventDefault();setFinished(true)}} className="space-y-5">{MOCK_EXAM.map((q,i)=><fieldset key={i} className="glass p-5"><legend className="px-2 text-lg font-semibold">{i+1}. {q.prompt}</legend><div className="mt-4 grid gap-2">{q.options.map((opt,oi)=><label key={oi} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm ${answers[i]===oi?'border-dps-green bg-dps-green/10':'border-white/10'}`}><input type="radio" name={`question-${i}`} checked={answers[i]===oi} onChange={()=>setAnswers(x=>({...x,[i]:oi}))}/>{opt}</label>)}</div></fieldset>)}<button className="btn btn-primary w-full" type="submit">Finish and check my answers</button></form>}</div>}
 <p className="mt-6 text-sm text-slate-500">Prefer your own topics? <Link className="text-dps-neon hover:underline" to="/learn/custom-test">Generate a custom practice test</Link>. Continue learning in the <Link className="text-dps-neon hover:underline" to="/learn">course library</Link>.</p></main><Footer/></div>
}
