import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { Bug, BrainCircuit, Clock3, Flame, Gamepad2, RotateCcw, Trophy } from 'lucide-react'
import Navbar from '../components/layout/Navbar'
import Footer from '../components/layout/Footer'
import { GAME_BANK } from '../services/gameQuestions'
import { getLearningAuth, learningApi } from '../services/learningApi'
const ICONS={'bug-hunt':Bug,'output-detective':BrainCircuit,'syntax-sprint':Flame}
export default function PracticeGames(){
 const [mode,setMode]=useState(null),[index,setIndex]=useState(0),[answers,setAnswers]=useState([]),[remaining,setRemaining]=useState(0),[finished,setFinished]=useState(false),[saved,setSaved]=useState('')
 const [best,setBest]=useState(()=>{try{return JSON.parse(localStorage.getItem('dps.game.bests')||'{}')}catch{return{}}}),finishedRef=useRef(false)
 const selected=mode?GAME_BANK[mode]:null
 function finish(){if(finishedRef.current)return;finishedRef.current=true;setFinished(true)}
 useEffect(()=>{if(!mode||finished)return;const tick=setInterval(()=>setRemaining(s=>{if(s<=1){setTimeout(()=>finish(),0);return 0}return s-1}),1000);return()=>clearInterval(tick)},[mode,finished])
 const percent=selected?Math.round(selected.questions.reduce((sum,q,i)=>sum+(answers[i]===q.correct?1:0),0)/selected.questions.length*100):0
 useEffect(()=>{if(!finished||!mode)return;const next={...best,[mode]:Math.max(best[mode]||0,percent)};setBest(next);localStorage.setItem('dps.game.bests',JSON.stringify(next));if(getLearningAuth())learningApi('/games',{method:'POST',body:{gameId:mode,score:percent}}).then(()=>setSaved('Your informal practice score was saved to your profile.')).catch(()=>setSaved('The score is saved on this device; sign in later to save new runs.'))},[finished])
 function start(id){setMode(id);setIndex(0);setAnswers([]);setRemaining(GAME_BANK[id].duration);setFinished(false);setSaved('');finishedRef.current=false}
 function select(i){if(answers[index]!=null||finished)return;const next=[...answers];next[index]=i;setAnswers(next)}
 function next(){if(index===selected.questions.length-1)finish();else setIndex(i=>i+1)}
 return <div className="flex min-h-screen flex-col"><Navbar/><main className="mx-auto w-full max-w-6xl flex-1 px-4 py-10 sm:px-6"><span className="chip"><Gamepad2 size={14}/> Practice arcade</span><h1 className="mt-4 font-display text-3xl font-bold">Make learning <span className="text-gradient">addictive.</span></h1><p className="mt-3 text-slate-400">Fast-paced games that teach debugging, output prediction and basic syntax. No sign-in required. These are learning scores, not official exam marks.</p>
 {!mode?<div className="mt-10 grid gap-5 md:grid-cols-3">{Object.entries(GAME_BANK).map(([id,g])=>{const Icon=ICONS[id];return <div key={id} className="glass group flex flex-col p-6 transition-all hover:-translate-y-1 hover:border-dps-green/40"><div className="mb-5 grid h-14 w-14 place-items-center rounded-2xl bg-gradient-to-br from-emerald-500/20 to-sky-500/20 text-dps-neon"><Icon size={28}/></div><h2 className="text-xl font-semibold">{g.title}</h2><p className="mt-2 flex-1 text-sm text-slate-400">{g.subtitle}</p><p className="mt-4 text-xs text-slate-500">{g.questions.length} rounds • {g.duration} seconds • Best {best[id]??'—'}%</p><button className="btn btn-primary mt-4" onClick={()=>start(id)}>Play now</button></div>})}</div>:
 <div className="glass mt-9 max-w-3xl overflow-hidden p-5 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="text-xs text-dps-neon">{selected.title}</span><h2 className="text-xl font-semibold">{finished?'Round complete!':`Question ${index+1} of ${selected.questions.length}`}</h2></div><span className={`chip ${remaining<=20?'border-red-500 text-red-300':'border-dps-green/30 text-dps-neon'}`}><Clock3 size={14}/> {remaining}s</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-dps-green transition-all" style={{width:`${(finished?selected.questions.length:index)/selected.questions.length*100}%`}}/></div>
 {finished?<div className="py-8 text-center"><Trophy className="mx-auto text-dps-gold" size={50}/><p className="mt-4 text-5xl font-bold text-dps-neon">{percent}%</p><p className="mt-2 text-slate-400">{selected.questions.filter((q,i)=>answers[i]===q.correct).length} out of {selected.questions.length} correct. {saved}</p><div className="mt-6 flex justify-center gap-2"><button className="btn btn-primary" onClick={()=>start(mode)}><RotateCcw size={16}/> Play again</button><button className="btn btn-ghost" onClick={()=>setMode(null)}>Choose another</button></div></div>:<><pre className="mt-8 whitespace-pre-wrap rounded-xl bg-black/20 p-5 font-mono text-lg text-slate-100">{selected.questions[index].prompt}</pre><div className="mt-5 grid gap-3">{selected.questions[index].options.map((opt,i)=>{const chosen=answers[index],correct=selected.questions[index].correct;return <button className={`rounded-xl border p-4 text-left text-sm transition ${chosen==null?'border-white/10 hover:border-emerald-500/40 hover:bg-white/5':i===correct?'border-emerald-400 bg-emerald-500/15':i===chosen?'border-red-400 bg-red-500/10':'border-white/10 opacity-60'}`} disabled={chosen!=null} onClick={()=>select(i)} key={i}>{String.fromCharCode(65+i)}. {opt}</button>})}</div>{answers[index]!=null&&<div className="mt-5 rounded-xl border border-dps-green/30 bg-emerald-500/5 p-4"><b className="text-dps-neon">{answers[index]===selected.questions[index].correct?'Correct!':'Good try — learn the rule.'}</b><p className="mt-1 text-sm text-slate-300">{selected.questions[index].explanation}</p><button className="btn btn-primary mt-4" onClick={next}>{index===selected.questions.length-1?'Finish game':'Next question →'}</button></div>}</>}
 </div>}
 <p className="mt-8 text-sm text-slate-400">Prefer the real editor? <Link to="/student/practice/python" className="text-dps-neon hover:underline">Open Practice IDE</Link>. For a timed exercise, <Link className="text-dps-neon hover:underline" to="/learn/mock-exam">try the Class IX mock exam</Link> or <Link to="/learn/arcade" className="text-dps-neon hover:underline">play interactive arcade missions</Link>.</p></main><Footer/></div>
}
