import Breadcrumbs from '../components/common/Breadcrumbs'
import {Spinner} from '../components/common/Feedback'
import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, Download, ExternalLink, ShieldCheck } from 'lucide-react'
import Navbar from '../components/layout/Navbar'
import Footer from '../components/layout/Footer'
import StudyNotes from '../components/common/StudyNotes'
import { BOOKS, STARTER_LESSONS, STARTER_QUIZZES, readProgress, saveProgress } from '../services/starterCourses'
import { getLearningAuth, learningApi } from '../services/learningApi'

export default function SelfStudyCourse({ teacherCourse = false }) {
 const {lang,id}=useParams(),key=teacherCourse?`teacher:${id}`:lang,book=BOOKS[lang]
 const [loading,setLoading]=useState(teacherCourse)
 const [course,setCourse]=useState(null),[joinCode,setJoinCode]=useState(''),[joining,setJoining]=useState(false),[error,setError]=useState('')
 const [progress,setProgress]=useState(()=>readProgress()[key]||{}),[index,setIndex]=useState(0),[answers,setAnswers]=useState({}),[result,setResult]=useState(null),[busy,setBusy]=useState(false)
 useEffect(()=>{setProgress(readProgress()[key]||{});setIndex(0);setAnswers({});setResult(null);
 if(teacherCourse && getLearningAuth()){learningApi(`/courses/${encodeURIComponent(id)}`).then(x=>{setCourse(x.course);setProgress({completed:x.course.completedLessons||[]})}).catch(e=>setError(e.message)).finally(()=>setLoading(false))}
 },[key,teacherCourse,id])
 if(!teacherCourse&&!book)return <div className="p-12"><Link to="/learn">Return to the catalog</Link></div>
 const lessons=teacherCourse?(course?.lessons||[]):STARTER_LESSONS[lang], quiz=teacherCourse?(course?.quiz||[]):STARTER_QUIZZES[lang]
 const done=teacherCourse?(progress.completed||[]):(progress.completed||[])
 async function complete(){ if(done.includes(index))return;
  try{let completed=[...new Set([...done,index])].sort((a,b)=>a-b);if(teacherCourse){const x=await learningApi(`/courses/${encodeURIComponent(id)}/lessons/${index}/complete`,{method:'POST',body:{}});completed=x.completedLessons} else saveProgress(key,{completed});setProgress(p=>({...p,completed}));setError('') }catch(e){setError(e.message)} }
 async function join(e){e.preventDefault();setJoining(true);setError('');try{await learningApi(`/courses/${encodeURIComponent(id)}/join`,{method:'POST',body:{joinCode}});let x=await learningApi(`/courses/${encodeURIComponent(id)}`);setCourse(x.course);setProgress({completed:x.course.completedLessons||[]})}catch(e){setError(e.message)}finally{setJoining(false)}}
 async function submitQuiz(e){e.preventDefault();setBusy(true);setError('');try{const submitted=quiz.map((_,i)=>Number.isInteger(answers[i])?answers[i]:-1);if(teacherCourse){let x=await learningApi(`/courses/${encodeURIComponent(id)}/quiz`,{method:'POST',body:{answers:submitted}});setResult(x)}else{const correct=quiz.reduce((n,q,i)=>n+(submitted[i]===q.answerIndex?1:0),0);const percent=Math.round(correct/quiz.length*100);setResult({score:percent,correct,total:quiz.length,informal:true});saveProgress(key,{bestScore:Math.max(percent,readProgress()[key]?.bestScore||0),lastAttempt:Date.now()})}}
 catch(e){setError(e.message)}finally{setBusy(false)}}
 if(teacherCourse&&!getLearningAuth())return <div className="flex min-h-screen flex-col"><Navbar/><main className="mx-auto w-full max-w-3xl flex-1 p-8"><h1 className="text-2xl font-bold">Join a teacher course</h1><p className="mt-3 text-slate-400">To share quiz progress with your course teacher, create a nickname-only practice profile and enter the course code they gave you.</p><Link to="/learn/profile" className="btn btn-primary mt-6">Sign in to practice profile</Link></main><Footer/></div>
 if(teacherCourse&&loading&&getLearningAuth())return <div className="flex min-h-screen flex-col"><Navbar/><main className="mx-auto w-full max-w-3xl flex-1 p-8"><Breadcrumbs/><h1 className="text-2xl font-semibold">Your teacher course</h1><Spinner label="Loading course lessons…"/></main><Footer/></div>
 if(teacherCourse&&!course)return <div className="flex min-h-screen flex-col"><Navbar/><main className="mx-auto w-full max-w-xl flex-1 p-8"><h1 className="text-2xl font-bold">Enroll in a teacher course</h1><p className="mt-3 text-slate-400">Use the private enrollment code issued by an authorized teacher. Your nickname and quiz result will be visible only to that course's teacher.</p><form onSubmit={join} className="glass mt-6 space-y-4 p-6"><label className="block text-sm">Enrollment code<input className="input mt-2" type="password" required value={joinCode} onChange={e=>setJoinCode(e.target.value)} /></label>{error&&<p className="text-red-300" role="alert">{error}</p>}<button className="btn btn-primary" disabled={joining}>{joining?'Checking...':'Join course'}</button></form></main><Footer/></div>
 return <div className="flex min-h-screen flex-col"><Navbar/><main className="mx-auto w-full max-w-6xl flex-1 px-4 py-10 sm:px-6"><Breadcrumbs/><Link to="/learn" className="flex items-center gap-2 text-sm text-slate-400 hover:text-dps-neon"><ArrowLeft size={14}/> Course library</Link><div className="mt-6 flex flex-wrap items-end justify-between gap-5"><div><span className="chip">{teacherCourse?`Teacher course · Class ${course.className}`:'Free self-paced course'}</span><h1 className="mt-4 font-display text-3xl font-bold">{teacherCourse?course.title:book.name+' Foundations'}</h1><p className="mt-2 max-w-2xl text-slate-400">{teacherCourse?course.summary:'Short practical lessons, confidence-building exercises and a mini quiz at the end.'}</p></div>{!teacherCourse&&<a href={book.pdf} download className="btn btn-ghost"><Download size={17}/> Get PDF cheat sheet</a>}</div>
 <div className="mt-8 grid gap-6 lg:grid-cols-[260px,1fr]"><aside className="glass h-fit p-4"><h2 className="mb-4 flex gap-2 font-semibold"><BookOpen size={18} className="text-dps-neon"/> Your roadmap</h2><div className="space-y-2">{lessons.map((l,i)=><button type="button" onClick={()=>setIndex(i)} key={i} className={`flex w-full items-center gap-3 rounded-xl p-3 text-left text-sm ${index===i?'bg-dps-green/20 text-white':'text-slate-400 hover:bg-white/5'}`}><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full text-xs ${done.includes(i)?'bg-dps-green text-white':'bg-white/10'}`}>{done.includes(i)?<CheckCircle2 size={15}/>:i+1}</span>{l.title}</button>)}</div><p className="mt-4 text-xs text-slate-500">{done.length} of {lessons.length} lessons completed</p></aside>
 <div className="space-y-6"><article className="glass relative overflow-hidden p-6 sm:p-8 animate-fade-up"><div className="absolute right-0 top-0 h-40 w-40 rounded-full bg-dps-green/10 blur-3xl" aria-hidden="true"/><p className="text-xs text-dps-neon">Lesson {index+1} / {lessons.length}</p><h2 className="mt-2 text-2xl font-bold">{lessons[index]?.title}</h2><div className="mt-6 whitespace-pre-wrap text-[15px] leading-8 text-slate-300">{lessons[index]?.body}</div><div className="mt-8 flex flex-wrap gap-3"><button className="btn btn-primary" type="button" disabled={done.includes(index)} onClick={complete}><CheckCircle2 size={16}/>{done.includes(index)?'Lesson completed':'Mark lesson complete'}</button>{index<lessons.length-1&&<button onClick={()=>setIndex(index+1)} className="btn btn-ghost">Next lesson <ArrowRight size={15}/></button>}</div></article>
 {!teacherCourse&&<div className="glass p-6"><h3 className="font-semibold">Further reading</h3><div className="mt-3 flex flex-wrap gap-2"><a className="btn btn-ghost btn-sm" href={book.official} target="_blank" rel="noreferrer">Reference guide <ExternalLink size={14}/></a><a className="btn btn-ghost btn-sm" href={book.external} target="_blank" rel="noreferrer">Free learning resource <ExternalLink size={14}/></a><Link to={`/student/practice/${lang}`} className="btn btn-primary btn-sm">Try in IDE</Link></div></div>}
 {teacherCourse&&course.resources?.length>0&&<div className="glass p-6"><h3 className="font-semibold">Teacher resources</h3>{course.resources.map((r,i)=><a className="mt-3 block text-dps-neon hover:underline" key={i} href={r.url} rel="noreferrer noopener" target="_blank">{r.title} ↗</a>)}</div>}
 <StudyNotes id={key} title={teacherCourse?course.title:book.name}/><section className="glass p-6"><div className="mb-5 flex items-center gap-2"><ShieldCheck className="text-dps-gold"/><h2 className="text-xl font-bold">End-of-course quiz</h2></div>{done.length!==lessons.length?<p className="text-sm text-slate-400">Finish all {lessons.length} lessons to unlock {quiz.length} mini questions. You can revisit any lesson first.</p>:result?<div className="rounded-xl border border-dps-green/30 bg-emerald-500/10 p-5"><p className="text-3xl font-bold text-dps-neon">{result.score}%</p><p className="mt-2 text-sm">{result.correct} out of {result.total} correct. {teacherCourse?'Your course teacher can review this score.':'Practice only; this is not an official mark or grade.'}</p><button className="btn btn-ghost btn-sm mt-4" onClick={()=>{setResult(null);setAnswers({})}}>Try again</button></div>:<form onSubmit={submitQuiz} className="space-y-6">{quiz.map((q,qi)=><fieldset key={qi} className="rounded-xl border border-white/10 p-4"><legend className="px-1 font-medium">{qi+1}. {q.prompt}</legend><div className="mt-3 grid gap-2">{q.options.map((opt,oi)=><label key={oi} className={`flex cursor-pointer items-center gap-3 rounded-lg border p-3 text-sm transition ${answers[qi]===oi?'border-dps-green bg-dps-green/10':'border-white/10 hover:border-white/30'}`}><input type="radio" name={`q${qi}`} checked={answers[qi]===oi} onChange={()=>setAnswers({...answers,[qi]:oi})} required/>{opt}</label>)}</div></fieldset>)}<button type="submit" disabled={busy||quiz.some((_,i)=>!Number.isInteger(answers[i]))} className="btn btn-primary">{busy?'Checking...':'Submit quiz'}</button></form>}{error&&<p className="mt-4 text-red-300" role="alert">{error}</p>}</section>
 </div></div></main><Footer/></div>
}
