import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Award, BookOpen, LogOut, ShieldCheck, UserRound } from 'lucide-react'
import Navbar from '../components/layout/Navbar'
import Footer from '../components/layout/Footer'
import { learningApi, clearLearningAuth, getLearningAuth, saveLearningAuth } from '../services/learningApi'
import { BOOKS, readProgress, STARTER_LESSONS } from '../services/starterCourses'

export default function StudentProfile(){
 const [auth,setAuth]=useState(getLearningAuth()),[mode,setMode]=useState('register'),[form,setForm]=useState({handle:'',password:'',className:'IX',acknowledgePrototype:false}),[error,setError]=useState(''),[loading,setLoading]=useState(false),[stats,setStats]=useState(null),[games,setGames]=useState([]),[courses,setCourses]=useState([])
 useEffect(()=>{if(!auth?.token)return;learningApi('/me').then(x=>{setStats(x.stats);setAuth(a=>({...a,profile:x.profile}))}).catch(e=>{setError(e.message);if(e.status===401){clearLearningAuth();setAuth(null)}});learningApi('/games').then(x=>setGames(x.results)).catch(()=>{});learningApi('/courses/my').then(x=>setCourses(x.courses)).catch(()=>{})},[auth?.token])
 async function submit(e){e.preventDefault();setLoading(true);setError('');try{const result=await learningApi(mode==='register'?'/register':'/login',{method:'POST',body:mode==='register'?form:{handle:form.handle,password:form.password}});saveLearningAuth(result);setAuth(result)}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function erase(){if(!window.confirm('Permanently delete your nickname profile and saved practice scores? This cannot be undone.'))return;const phrase=window.prompt('To confirm, type DELETE MY PRACTICE DATA');if(phrase!=='DELETE MY PRACTICE DATA')return;try{await learningApi('/me',{method:'DELETE',body:{confirm:phrase}});clearLearningAuth();setAuth(null);setStats(null);setError('')}catch(e){setError(e.message)}}
 const progress=readProgress(),achievements=Object.entries(progress).reduce((sum,[k,v])=>sum+(v.completed||[]).length,0)
 return <div className="flex min-h-screen flex-col"><Navbar/><main className="mx-auto w-full max-w-5xl flex-1 px-4 py-10 sm:px-6"><span className="chip"><UserRound size={14}/> Optional practice identity</span><h1 className="mt-4 text-3xl font-bold">Your learning profile</h1><p className="mt-3 max-w-3xl text-slate-400">Use a nickname rather than your real name. You never need a practice profile to use the IDE, mini games or sample lessons. School exams remain a completely separate, passcode-based flow.</p>
 {!auth?<form onSubmit={submit} className="glass mt-8 max-w-lg space-y-4 p-7"><div className="flex gap-2"><button type="button" onClick={()=>setMode('register')} className={`btn btn-sm ${mode==='register'?'btn-primary':'btn-ghost'}`}>Create practice profile</button><button type="button" onClick={()=>setMode('login')} className={`btn btn-sm ${mode==='login'?'btn-primary':'btn-ghost'}`}>Sign in</button></div><label className="block text-sm">Nickname (not your full name)<input autoComplete="username" className="input mt-1" maxLength={32} pattern="[a-zA-Z0-9_-]{3,32}" required value={form.handle} onChange={e=>setForm({...form,handle:e.target.value})}/></label><label className="block text-sm">Password<input autoComplete={mode==='register'?'new-password':'current-password'} className="input mt-1" type="password" minLength={mode==='register'?10:1} maxLength={128} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>
 {mode==='register'&&<><label className="block text-sm">Class<select className="input mt-1" value={form.className} onChange={e=>setForm({...form,className:e.target.value})}>{['VI','VII','VIII','IX','X','XI','XII'].map(v=><option key={v}>{v}</option>)}</select></label><label className="flex gap-2 text-xs leading-5 text-slate-300"><input className="mt-1" required type="checkbox" checked={form.acknowledgePrototype} onChange={e=>setForm({...form,acknowledgePrototype:e.target.checked})}/> I understand this is an independent prototype, not an official school portal. I'll avoid entering personal information and ask a parent or authorized teacher before sharing coursework.</label></>}
 {error&&<p className="text-red-300" role="alert">{error}</p>}<button className="btn btn-primary w-full" disabled={loading}>{loading?'Please wait...':mode==='register'?'Create profile':'Sign in'}</button><p className="text-xs text-slate-500">Profiles use nickname + password only; no email or permanent school roll number. Session ends when this browser session closes.</p></form>:
 <div className="mt-8 space-y-6"><div className="glass p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-dps-neon">Signed in as</p><h2 className="mt-1 text-2xl font-bold">{auth.profile?.handle}</h2><p className="text-sm text-slate-400">Class {auth.profile?.className||'IX'} • Personal practice account</p></div><button className="btn btn-ghost" onClick={()=>{clearLearningAuth();setAuth(null);setStats(null)}}><LogOut size={16}/> Sign out</button></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[['Guide lessons finished',achievements],['Games played',stats?.game_attempts||0],['Teacher courses joined',stats?.courses_joined||0]].map(([l,n])=><div key={l} className="rounded-xl bg-white/5 p-4"><p className="text-2xl font-bold text-dps-neon">{n}</p><p className="mt-1 text-sm text-slate-400">{l}</p></div>)}</div></div>
 <div className="grid gap-5 md:grid-cols-2"><section className="glass p-6"><h3 className="mb-4 flex items-center gap-2 font-semibold"><BookOpen size={18}/> Study progress on this device</h3>{Object.entries(BOOKS).map(([key,b])=><div key={key} className="mb-3 flex justify-between gap-3 text-sm"><Link to={`/learn/course/${key}`} className="text-slate-200 hover:text-dps-neon">{b.name}</Link><span className="text-slate-500">{progress[key]?.completed?.length||0}/{STARTER_LESSONS[key].length}</span></div>)}<p className="mt-4 text-xs text-slate-500">Built-in guide progress stays on this device, not visible to teachers.</p></section><section className="glass p-6"><h3 className="mb-4 flex items-center gap-2 font-semibold"><Award size={18}/> Practice game history</h3>{games.length?games.slice(0,8).map((g,i)=><p className="mb-3 flex justify-between text-sm" key={i}><span>{g.game_id.replaceAll('-',' ')}</span><b className="text-dps-neon">{g.score}%</b></p>):<p className="text-sm text-slate-400">No games saved yet. <Link to="/learn/games" className="text-dps-neon">Play a mini game</Link>.</p>}</section></div><section className="glass p-6"><h3 className="font-semibold">Joined teacher courses</h3>{courses.length?<div className="mt-4 space-y-3">{courses.map(c=><Link className="flex justify-between rounded-xl border border-white/10 p-3 hover:border-dps-green/40" to={`/learn/teacher-course/${c.id}`} key={c.id}>{c.title}<span className="text-dps-neon">{c.bestScore==null?'In progress':`${c.bestScore}%`}</span></Link>)}</div>:<p className="mt-2 text-sm text-slate-400">When an authorized teacher shares a join code, enroll through the <Link to="/learn" className="text-dps-neon">course library</Link>.</p>}</section><button type="button" onClick={erase} className="btn btn-ghost btn-sm border-red-500/30 text-red-300">Delete my practice profile and server-side scores</button></div>}
 <div className="mt-8 flex items-start gap-3 rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-4 text-sm"><ShieldCheck className="shrink-0 text-dps-neon" size={18}/><span>Teacher exams still use separate exam sessions. A practice account cannot access teacher records or official examination data.</span></div></main><Footer/></div>
}
