import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Download, LogOut, Monitor, ShieldCheck, UserRound } from 'lucide-react'
import Navbar from '../components/layout/Navbar'
import Footer from '../components/layout/Footer'
import { useAccount } from '../components/common/AccountBootstrap'
import { accountApi, deviceLearningProgress, refreshAccount, signOutAccount } from '../services/accountApi'
import { updateAccount } from '../services/session'
export const AVATARS = { book: '📚', leaf: '🌿', star: '⭐', rocket: '🚀', fox: '🦊', owl: '🦉', planet: '🪐', robot: '🤖' }
const date = x => x ? new Date(x).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' }) : '—'
export default function StudentAccountProfile() {
 const auth = useAccount(), navigate = useNavigate(), [data, setData] = useState(null), [devices, setDevices] = useState([]), [form, setForm] = useState({ displayName: '', avatar: 'book', theme: 'light' }), [password, setPassword] = useState({ currentPassword: '', newPassword: '', confirm: '' }), [error, setError] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false), [review, setReview] = useState(null)
 const load = async () => { const [p, s] = await Promise.all([accountApi('/student/profile'), accountApi('/student/sessions')]); setData(p); setDevices(s.sessions); setForm({ displayName: p.student.displayName, avatar: p.student.avatar, theme: p.student.theme }) }
 useEffect(() => { load().catch(e => setError(e.message)) }, [])
 async function act(fn, msg) { setBusy(true); setError(''); setMessage(''); try { await fn(); if (msg) setMessage(msg) } catch (e) { setError(e.message) } finally { setBusy(false) } }
 async function importProgress(consent) { let practiceToken; try { practiceToken = JSON.parse(sessionStorage.getItem('dps.learning.profile'))?.token } catch { /* absent */ } await accountApi('/student/learning/import', { method: 'POST', body: { consent, ...(consent ? { progress: deviceLearningProgress(), ...(practiceToken ? { practiceToken } : {}) } : {}) } }); await refreshAccount(); await load() }
 const s = data?.student || auth.student
 return <div className="flex min-h-screen flex-col"><Navbar /><main className="account-page mx-auto w-full max-w-6xl flex-1 px-5 py-10"><header className="mb-7 flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-4"><span className="account-avatar" aria-label={`${s?.avatar || 'book'} avatar`}>{AVATARS[s?.avatar] || '📚'}</span><div><span className="chip"><UserRound size={13} /> STUDENT ACCOUNT</span><h1 className="mt-2 text-3xl font-semibold">Hello, {s?.displayName || s?.name?.split(' ')[0]}.</h1><p className="mt-1 text-sm text-slate-400">Class {s?.className} · Section {s?.section}</p></div></div><div className="flex gap-2"><Link className="btn btn-primary" to="/student/join">Join an exam</Link><button className="btn btn-ghost" disabled={busy} onClick={() => act(async () => { await signOutAccount(); navigate('/student/login') })}><LogOut size={16} /> Sign out</button></div></header>{error && <p className="account-error mb-4" role="alert">{error}</p>}{message && <p className="mb-4 rounded-xl border border-dps-green/30 p-4" role="status">{message}</p>}{auth.syncError && <p role="status" className="mb-4 text-sm">{auth.syncError}</p>}
 {!s?.learningImportDecided && <section className="account-import glass mb-6 p-6" aria-labelledby="import-title"><ShieldCheck size={24} className="text-dps-green" /><div><h2 id="import-title" className="text-lg font-semibold">Bring your learning progress with you?</h2><p className="mt-2 text-sm text-slate-400">Import course progress, practice test results and game scores saved on this device, plus a signed-in practice profile. Import only if this is your own progress. School exam results stay separate.</p><div className="mt-4 flex flex-wrap gap-3"><button className="btn btn-primary btn-sm" disabled={busy} onClick={() => act(() => importProgress(true), 'Your practice progress was imported.')}>Yes, import my progress</button><button className="btn btn-ghost btn-sm" disabled={busy} onClick={() => act(() => importProgress(false), 'You will start with fresh account progress.')}>No, start fresh</button></div></div></section>}
 <div className="grid gap-6 lg:grid-cols-2"><section className="glass p-6"><h2 className="text-xl font-semibold">School details</h2><dl className="account-details mt-5">{[['Full name',s?.name],['Username',s?.username],['Roll number',s?.rollNumber],['Class',s?.className],['Section',s?.section],['School email',s?.schoolEmail || 'Not provided']].map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="mt-5 text-sm text-slate-400">Ask your teacher to change this.</p></section><form className="glass space-y-4 p-6" onSubmit={e => { e.preventDefault(); act(async () => { const r = await accountApi('/student/profile', { method: 'PUT', body: form }); updateAccount({ student: r.student }); await load(); window.dispatchEvent(new CustomEvent('dps-theme-change', { detail: form.theme })) }, 'Profile saved.') }}><h2 className="text-xl font-semibold">Make it yours</h2><label className="block text-sm">Display name or nickname<input className="input mt-2" value={form.displayName} onChange={e => setForm({ ...form, displayName: e.target.value })} maxLength={40} autoComplete="nickname" /></label><fieldset><legend className="mb-2 text-sm">Choose an avatar</legend><div className="flex flex-wrap gap-2">{Object.entries(AVATARS).map(([id, icon]) => <label key={id} className={`avatar-choice ${form.avatar === id ? 'selected' : ''}`}><input className="sr-only" type="radio" name="avatar" value={id} checked={form.avatar === id} onChange={() => setForm({ ...form, avatar: id })} /><span aria-hidden="true">{icon}</span><span className="sr-only">{id}</span></label>)}</div></fieldset><label className="block text-sm">Theme<select className="input mt-2" value={form.theme} onChange={e => setForm({ ...form, theme: e.target.value })}><option value="light">Light</option><option value="dark">Dark</option><option value="system">Use device setting</option></select></label><button className="btn btn-primary" disabled={busy}>Save profile</button></form>
 <section className="glass p-6 lg:col-span-2"><h2 className="text-xl font-semibold">Exam history</h2><p className="mt-2 text-sm text-slate-400">Past exams appear here once your teacher releases the results. Unfinished reviews have no score yet.</p>{data?.history.length ? <div className="mt-5 overflow-x-auto"><table className="table-base"><thead><tr><th>Exam</th><th>Date</th><th>Status</th><th>Score</th><th>Work</th></tr></thead><tbody>{data.history.map(h => <tr key={h.submission_id}><td>{h.title}</td><td>{date(h.date)}</td><td className="capitalize">{h.review_status}</td><td>{h.score == null ? 'Awaiting review' : `${h.score} / ${h.total_marks}`}</td><td><button className="btn btn-ghost btn-sm" onClick={() => act(async () => setReview(await accountApi('/student/submissions/' + h.submission_id)))}>View</button></td></tr>)}</tbody></table></div> : <p className="mt-5 text-sm text-slate-400">No released exam results yet.</p>}{review && <div className="mt-5 rounded-xl border border-white/10 p-4"><div className="flex justify-between gap-3"><h3 className="font-semibold">{review.submission.title}</h3><button className="btn btn-ghost btn-sm" onClick={() => setReview(null)}>Close</button></div>{review.answers.map(a => <article className="mt-4 border-t border-white/10 pt-3" key={a.question_id}><h4>{a.title}</h4><pre className="mt-2 whitespace-pre-wrap break-words text-sm">{a.answer_text || a.code || 'File answer'}</pre><p className="mt-2 text-sm">{a.marks_awarded == null ? 'Awaiting review' : `${a.marks_awarded} / ${a.marks}`}{a.remarks ? ` · ${a.remarks}` : ''}</p></article>)}</div>}</section>
 <section className="glass p-6"><h2 className="text-xl font-semibold">Learning progress</h2><div className="mt-5 grid grid-cols-3 gap-3">{[['Lessons',Object.values(auth.progress.courses).reduce((n,p)=>n+(p.completed?.length||0),0)],['Mock tests',auth.progress.mocks.length+auth.progress.customTests.length],['Games',Object.keys(auth.progress.games).length]].map(([label,n]) => <div key={label} className="rounded-xl border border-white/10 p-4"><strong className="text-2xl">{n}</strong><p className="mt-1 text-xs text-slate-400">{label}</p></div>)}</div><p className="mt-4 text-sm text-slate-400">New practice progress syncs to your account. Practice scores are informal.</p><Link to="/learn" className="btn btn-ghost mt-4">Open Learning Hub</Link></section>
 <form className="glass space-y-4 p-6" onSubmit={e => { e.preventDefault(); act(async () => { if (password.confirm !== password.newPassword) throw new Error('The new passwords do not match.'); await accountApi('/student/set-password', { method: 'POST', body: { currentPassword: password.currentPassword, newPassword: password.newPassword } }); setPassword({ currentPassword: '', newPassword: '', confirm: '' }); await load() }, 'Password changed. Other devices were signed out.') }}><h2 className="text-xl font-semibold">Change password</h2>{[['Current password','currentPassword'],['New password','newPassword'],['Confirm new password','confirm']].map(([label,key]) => <label key={key} className="block text-sm">{label}<input className="input mt-2" type="password" required minLength={key==='currentPassword'?1:12} maxLength={72} autoComplete={key==='currentPassword'?'current-password':'new-password'} value={password[key]} onChange={e=>setPassword({...password,[key]:e.target.value})}/></label>)}<button className="btn btn-primary" disabled={busy}>Change password</button></form>
 <section className="glass p-6"><h2 className="flex items-center gap-2 text-xl font-semibold"><Monitor size={21}/> Signed-in devices</h2><ul className="mt-4 space-y-3">{devices.map(d => <li key={d.id} className="rounded-xl border border-white/10 p-3"><p className="text-sm font-medium">{d.device_label} {d.current && <span className="text-dps-green">· This device</span>}</p><p className="mt-1 text-xs text-slate-400">Last used {date(d.last_seen_at)} · Expires {date(d.expires_at)}</p></li>)}</ul><button className="btn btn-ghost mt-4" disabled={busy} onClick={()=>act(async()=>{await accountApi('/student/sessions/revoke-others',{method:'POST'});await load()},'Other devices were signed out.')}>Sign out of all other devices</button></section>
 <section className="glass p-6"><h2 className="text-xl font-semibold">Privacy</h2><p className="mt-3 text-sm text-slate-400">Download a copy of your profile and records. Account deletion needs teacher approval so exam records are preserved.</p><div className="mt-5 flex flex-col items-start gap-3"><button className="btn btn-ghost" disabled={busy} onClick={()=>act(()=>accountApi('/student/data',{download:true}))}><Download size={16}/> Download my data (JSON)</button><button className="btn btn-ghost" disabled={busy||data?.deletionRequest?.status==='pending'} onClick={()=>act(async()=>{await accountApi('/student/deletion-request',{method:'POST'});await load()},'Your teacher will review your request.')}>{data?.deletionRequest?.status==='pending'?'Deletion request pending':'Request account deletion'}</button></div></section></div></main><Footer/></div>
}
