import { useEffect, useRef, useState } from 'react'
import { MessageCircle, Send, ExternalLink, ShieldCheck } from 'lucide-react'
import { io } from 'socket.io-client'
import { API_BASE_URL } from '../config'
import { getTeacherToken } from '../services/session'
import { learningApi } from '../services/learningApi'
import { formatDateTime } from '../utils/format'
export default function TeacherCommunity(){
 const [messages,setMessages]=useState([]),[text,setText]=useState(''),[url,setUrl]=useState(''),[state,setState]=useState('connecting'),[error,setError]=useState(''),[sending,setSending]=useState(false)
 const listEnd=useRef(null)
 useEffect(()=>{let active=true;learningApi('/teacher/community',{teacher:true}).then(x=>active&&setMessages(x.messages)).catch(e=>setError(e.message));const socket=io(API_BASE_URL,{auth:{token:getTeacherToken()},transports:['websocket','polling']});socket.on('connect',()=>socket.emit('teacher:communityJoin'));socket.on('teachers:communityJoined',()=>setState('online'));socket.on('teachers:message',m=>setMessages(list=>list.some(x=>x.id===m.id)?list:[...list,m].slice(-100)));socket.on('disconnect',()=>setState('reconnecting'));socket.on('connect_error',()=>setState('offline (messages still work)'));return()=>{active=false;socket.disconnect()}},[])
 useEffect(()=>{listEnd.current?.scrollIntoView({behavior:'smooth',block:'end'})},[messages.length])
 async function send(e){e.preventDefault();setSending(true);setError('');try{const r=await learningApi('/teacher/community',{teacher:true,method:'POST',body:{body:text,resourceUrl:url||undefined}});setMessages(v=>v.some(x=>x.id===r.message.id)?v:[...v,r.message]);setText('');setUrl('')}catch(e){setError(e.message)}finally{setSending(false)}}
 return <div className="mx-auto max-w-5xl"><span className="chip"><MessageCircle size={14}/> Verified teacher-only discussion</span><h1 className="mt-4 text-3xl font-bold">Staff collaboration room</h1><p className="mt-3 max-w-3xl text-slate-400">Share teaching ideas, free resource links and handout references with authorized teachers. Messages are saved and delivered live through the backend. Do not discuss identifiable pupils or confidential exam answers here.</p><div className="mt-4 flex gap-2 text-xs text-slate-400"><ShieldCheck size={15} className="text-dps-neon"/> Only active teacher accounts can see or post messages. Connection: {state}</div>
 <div className="glass mt-6 overflow-hidden"><div className="max-h-[55vh] min-h-[320px] space-y-4 overflow-y-auto p-5" role="log" aria-label="Teacher discussion messages">{messages.length===0&&<div className="py-12 text-center text-slate-400">No discussion messages yet. Start by sharing a helpful lesson idea.</div>}{messages.map(m=><article key={m.id} className="rounded-xl border border-white/10 bg-white/[0.03] p-4"><div className="flex flex-wrap justify-between gap-2"><b className="text-sm text-dps-neon">{m.author}</b><time className="text-xs text-slate-500">{formatDateTime(m.created_at)}</time></div><p className="mt-2 whitespace-pre-wrap break-words text-sm text-slate-200">{m.body}</p>{m.resource_url&&<a className="mt-3 inline-flex items-center gap-2 text-sm text-dps-gold underline" href={m.resource_url} target="_blank" rel="noopener noreferrer">Shared resource <ExternalLink size={13}/></a>}</article>)}<div ref={listEnd}/></div><form onSubmit={send} className="space-y-3 border-t border-white/10 p-5"><label className="block text-sm">Message<textarea className="input mt-2" required maxLength={1000} minLength={1} value={text} onChange={e=>setText(e.target.value)} placeholder="Have a great idea for a Python lesson? Share it here." rows={3}/></label><label className="block text-xs text-slate-400">Optional HTTPS resource / handout link<input type="url" className="input mt-2" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..." /></label>{error&&<p role="alert" className="text-red-300">{error}</p>}<button type="submit" disabled={sending||!text.trim()} className="btn btn-primary"><Send size={15}/> {sending?'Sending...':'Send to staff'}</button></form></div></div>
}
