import { Spinner } from '../components/common/Feedback'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { BookPlus, Clipboard, FileText, Library, Loader2, Sparkles } from 'lucide-react'
import { getTeacherAuth } from '../services/session'
import { learningApi } from '../services/learningApi'
import { deriveCourseNotes, extractPdf, suggestWithFreeLocalAI } from '../services/handoutAssistant'
const empty={title:'',summary:'',language:'python',className:'IX',joinCode:'',lessons:[{title:'Lesson 1',body:''}],quiz:[{prompt:'',options:['','','',''],answerIndex:0}],resources:[]}
export default function TeacherCourses(){
 const [loading,setLoading]=useState(true)
 const [form,setForm]=useState(empty),[courses,setCourses]=useState([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[rawText,setRawText]=useState(''),[selected,setSelected]=useState(null),[results,setResults]=useState(null)
 const auth=getTeacherAuth(),admin=auth?.teacher?.role==='admin'
 const reload=()=>learningApi('/teacher/courses',{teacher:true}).then(x=>setCourses(x.courses)).catch(e=>setError(e.message)).finally(()=>setLoading(false))
 useEffect(()=>{reload()},[])
 const update=(key,val)=>setForm(f=>({...f,[key]:val})),updateLesson=(i,key,val)=>setForm(f=>({...f,lessons:f.lessons.map((l,j)=>j===i?{...l,[key]:val}:l)})),updateQuestion=(i,key,val)=>setForm(f=>({...f,quiz:f.quiz.map((q,j)=>j===i?{...q,[key]:val}:q)}))
 const generateCode=()=>update('joinCode',Array.from(crypto.getRandomValues(new Uint8Array(12)),v=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[v%32]).join(''))
 async function parsePdf(e){setError('');const file=e.target.files?.[0];if(!file)return;setBusy(true);try{setRawText(await (file.name.toLowerCase().endsWith('.pdf')?extractPdf(file):file.text()));setNotice(`Extracted ${file.name} locally. Review the text and generate editable study suggestions.`)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function suggestions(ai=false){setBusy(true);setError('');try{const r=ai?await suggestWithFreeLocalAI(rawText):{data:deriveCourseNotes(rawText),method:'keyword extraction'};if(r.available===false){setNotice(r.reason);return}const notes=r.data;const lessons=notes.lessons?.filter(l=>l.title?.length>=2&&l.body?.length>=20).slice(0,20),quiz=notes.quiz?.filter(q=>q.prompt?.length>=4&&q.options?.length===4&&Number.isInteger(q.answerIndex)).slice(0,20);setForm(f=>({...f,summary:String(notes.summary||'').slice(0,800),lessons:lessons?.length?lessons:f.lessons,quiz:quiz?.length?quiz:f.quiz}));setNotice(`Generated editable drafts using ${r.method}. Check EVERY answer against your handout before saving. No file was uploaded.`)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function create(e){e.preventDefault();setBusy(true);setError('');setNotice('');try{const result=await learningApi('/teacher/courses',{teacher:true,method:'POST',body:form});setNotice(`Draft created. Record this enrollment code securely: ${form.joinCode} — shown here only once. Publish the course after checking the quiz.`);setForm({...empty,lessons:[...empty.lessons],quiz:[{...empty.quiz[0],options:['','','','']} ]});reload()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function publish(id){try{await learningApi(`/teacher/courses/${id}/publish`,{teacher:true,method:'POST',body:{}});setNotice('Published. Give the enrollment code privately to your students.');reload()}catch(e){setError(e.message)}}
 async function showGrades(id){try{const d=await learningApi(`/teacher/courses/${id}/results`,{teacher:true});setResults(d);setSelected(id)}catch(e){setError(e.message)}}
 return <div className="mx-auto max-w-7xl space-y-8"><div><span className="chip"><Library size={14}/> Teacher-created courses</span><h1 className="mt-3 text-3xl font-bold">Learning studio</h1><p className="mt-2 max-w-3xl text-slate-400">Create lessons, add resource links, generate draft questions from text/PDFs locally, then review and publish. Only students who enter your private join code appear in your course report.</p></div>
 <div className="grid gap-6 xl:grid-cols-[1fr,340px]"><section className="glass p-6"><h2 className="flex gap-2 text-xl font-semibold"><BookPlus size={22} className="text-dps-neon"/> Create a course</h2><div className="mt-5 rounded-xl border border-dps-gold/20 bg-dps-gold/5 p-4"><h3 className="flex gap-2 font-semibold"><Sparkles size={18} className="text-dps-gold"/> Free handout assistant</h3><p className="mt-2 text-sm text-slate-300">Upload a text-based PDF or paste notes. Keyword extraction works in every browser; optional on-device AI works only where the browser provides a local language model. Neither requires an API key or silently sends handouts to a cloud AI.</p><input type="file" accept=".pdf,.txt,text/plain,application/pdf" className="mt-4 block w-full text-xs" onChange={parsePdf} aria-label="Choose a PDF or text handout"/><textarea className="input mt-3 min-h-32" value={rawText} onChange={e=>setRawText(e.target.value)} placeholder="Or paste a text handout here. Keep student-identifying information out of the document." maxLength={45000}/><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={()=>suggestions()} disabled={busy||rawText.length<150} className="btn btn-ghost btn-sm">Draft lessons + quiz</button><button type="button" onClick={()=>suggestions(true)} disabled={busy||rawText.length<150} className="btn btn-ghost btn-sm">Try free on-device AI</button></div><p className="mt-2 text-xs text-slate-500">Suggestions are not assessed or verified AI output. Always inspect answers before publishing.</p></div>
 <form className="mt-6 space-y-5" onSubmit={create}><div className="grid gap-4 md:grid-cols-2"><label className="block text-sm">Course title<input className="input mt-1" required maxLength={150} minLength={4} value={form.title} onChange={e=>update('title',e.target.value)} placeholder="Python loops and logic"/></label><label className="block text-sm">Subject / language<select className="input mt-1" value={form.language} onChange={e=>update('language',e.target.value)}>{['python','web','java','c','cpp','sql','blocks'].map(x=><option key={x} value={x}>{x.toUpperCase()}</option>)}</select></label><label className="block text-sm">Class<select className="input mt-1" value={form.className} onChange={e=>update('className',e.target.value)}>{['VI','VII','VIII','IX','X','XI','XII'].map(x=><option key={x}>{x}</option>)}</select></label><label className="block text-sm">Private enrollment code<span className="flex gap-2"><input className="input mt-1" minLength={10} maxLength={40} type="text" required value={form.joinCode} onChange={e=>update('joinCode',e.target.value)}/><button type="button" className="btn btn-ghost btn-sm mt-1" onClick={generateCode}>Generate</button></span></label></div><label className="block text-sm">Summary<textarea className="input mt-1" rows={3} value={form.summary} maxLength={800} onChange={e=>update('summary',e.target.value)}/></label>
 <div className="border-t border-white/10 pt-5"><h3 className="font-semibold">Lessons ({form.lessons.length})</h3>{form.lessons.map((l,i)=><div className="mt-3 space-y-2 rounded-xl border border-white/10 p-4" key={i}><input required minLength={2} className="input" placeholder={`Lesson ${i+1} title`} value={l.title} onChange={e=>updateLesson(i,'title',e.target.value)}/><textarea required minLength={20} maxLength={12000} rows={5} className="input" placeholder="Explain the topic, with examples..." value={l.body} onChange={e=>updateLesson(i,'body',e.target.value)}/></div>)}<button type="button" disabled={form.lessons.length>=20} className="btn btn-ghost btn-sm mt-3" onClick={()=>setForm(f=>({...f,lessons:[...f.lessons,{title:`Lesson ${f.lessons.length+1}`,body:''}]}))}>Add lesson</button></div>
 <div className="border-t border-white/10 pt-5"><h3 className="font-semibold">End-of-course questions ({form.quiz.length})</h3>{form.quiz.map((q,i)=><div className="mt-3 space-y-2 rounded-xl border border-white/10 p-4" key={i}><input className="input" minLength={4} required placeholder={`Question ${i+1}`} value={q.prompt} onChange={e=>updateQuestion(i,'prompt',e.target.value)}/><div className="grid gap-2 sm:grid-cols-2">{q.options.map((v,j)=><input className="input" key={j} value={v} minLength={1} maxLength={180} required placeholder={`Option ${j+1}`} onChange={e=>updateQuestion(i,'options',q.options.map((old,k)=>k===j?e.target.value:old))}/>)}</div><label className="block text-xs text-slate-400">Verified correct answer<select className="input mt-1" value={q.answerIndex} onChange={e=>updateQuestion(i,'answerIndex',Number(e.target.value))}>{q.options.map((_,k)=><option key={k} value={k}>Option {k+1}</option>)}</select></label></div>)}<button type="button" className="btn btn-ghost btn-sm mt-3" disabled={form.quiz.length>=20} onClick={()=>setForm(f=>({...f,quiz:[...f.quiz,{prompt:'',options:['','','',''],answerIndex:0}]}))}>Add question</button></div>
 <div className="border-t border-white/10 pt-5"><h3 className="font-semibold">Resource links</h3><p className="mb-3 text-xs text-slate-400">Link to approved HTTPS PDFs, reference websites or private handouts. File uploads require separate private storage.</p>{form.resources.map((r,i)=><div key={i} className="mb-3 grid gap-2 sm:grid-cols-2"><input className="input" placeholder="Resource title" value={r.title} onChange={e=>setForm(f=>({...f,resources:f.resources.map((x,j)=>j===i?{...x,title:e.target.value}:x)}))}/><input className="input" type="url" placeholder="https://..." value={r.url} onChange={e=>setForm(f=>({...f,resources:f.resources.map((x,j)=>j===i?{...x,url:e.target.value}:x)}))}/></div>)}<button type="button" className="btn btn-ghost btn-sm" onClick={()=>setForm(f=>({...f,resources:[...f.resources,{title:'',url:''}]}))} disabled={form.resources.length>=8}>Add resource</button></div>
 {error&&<p role="alert" className="text-sm text-red-300">{error}</p>}{notice&&<p role="status" className="rounded-xl border border-dps-green/20 bg-emerald-500/10 p-4 text-sm text-dps-neon">{notice}</p>}<button className="btn btn-primary" disabled={busy}>{busy?<Loader2 size={16} className="animate-spin"/>:<FileText size={16}/>} Save private draft</button></form></section>
 <aside className="space-y-5"><section className="glass p-5"><h2 className="font-semibold">Your courses</h2><p className="mt-1 text-xs text-slate-500">Drafts are private until you publish them.</p>{loading?<Spinner label="Loading your courses…"/>:courses.length===0?<p className="mt-4 text-sm text-slate-400">No courses yet.</p>:courses.map(c=><article className="mt-4 rounded-xl border border-white/10 p-4" key={c.id}><span className="chip">{c.published?'Published':'Draft'}</span><h3 className="mt-2 font-semibold">{c.title}</h3><p className="mt-1 text-xs text-slate-400">Class {c.className} • {c.lessonCount} lessons</p><div className="mt-4 flex flex-wrap gap-2">{!c.published&&<button className="btn btn-primary btn-sm" onClick={()=>publish(c.id)}>Publish</button>}<button className="btn btn-ghost btn-sm" onClick={()=>showGrades(c.id)}>Student scores</button></div></article>)}</section>{results&&<section className="glass p-5"><h3 className="font-semibold">Course results</h3><p className="mt-2 text-xs text-slate-400">Only enrolled nicknames; not official school marks.</p>{results.students.length===0?<p className="mt-4 text-sm text-slate-400">No students joined yet.</p>:results.students.map((s,i)=><div key={i} className="mt-3 flex flex-col gap-1 border-b border-white/5 pb-3 text-sm"><b>{s.handle}</b><span className="text-slate-400">Class {s.class_name} • {s.completed_lessons.length} lessons • Best {s.best_score??'—'}%</span></div>)}</section>}</aside></div></div>
}
