import { Spinner } from '../components/common/Feedback'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { BookPlus, Clipboard, FileText, Library, Loader2, Sparkles } from 'lucide-react'
import { getTeacherAuth } from '../services/session'
import { learningApi } from '../services/learningApi'
import { deriveCourseNotes, extractPdf, suggestWithFreeLocalAI } from '../services/handoutAssistant'
import CourseAiDesigner from '../components/teacher/CourseAiDesigner'
import { readExamWorkspace, teacherWorkspaceKey, writeExamWorkspace } from '../services/teacherExamWorkspace'
const empty={title:'',summary:'',language:'python',className:'IX',joinCode:'',lessons:[{title:'Lesson 1',body:''}],quiz:[{prompt:'',options:['','','',''],answerIndex:0}],resources:[]}
export default function TeacherCourses(){
 const [loading,setLoading]=useState(true)
 const workspaceKey=teacherWorkspaceKey('course-designer')
 const [form,setForm]=useState(()=>({...empty,...readExamWorkspace(workspaceKey)?.form,joinCode:''})),[courses,setCourses]=useState([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[rawText,setRawText]=useState(''),[selected,setSelected]=useState(null),[results,setResults]=useState(null)
 const [designer,setDesigner]=useState(true),[designerBusy,setDesignerBusy]=useState(false),[storageError,setStorageError]=useState(false),[editing,setEditing]=useState(()=>readExamWorkspace(workspaceKey)?.editing||null),[reviewed,setReviewed]=useState(false),[savedContent,setSavedContent]=useState(null)
 useEffect(()=>{const {joinCode,...safe}=form;setStorageError(!writeExamWorkspace(workspaceKey,{form:safe,editing}))},[form,editing,workspaceKey])
 useEffect(()=>setReviewed(false),[form])
 const currentContent=JSON.stringify(Object.fromEntries(Object.entries(form).filter(([key])=>key!=='joinCode')))
 const auth=getTeacherAuth(),admin=auth?.teacher?.role==='admin'
 const reload=()=>learningApi('/teacher/courses',{teacher:true}).then(x=>setCourses(x.courses)).catch(e=>setError(e.message)).finally(()=>setLoading(false))
 useEffect(()=>{reload()},[])
 const update=(key,val)=>{setReviewed(false);setForm(f=>({...f,[key]:val}))},updateLesson=(i,key,val)=>{setReviewed(false);setForm(f=>({...f,lessons:f.lessons.map((l,j)=>j===i?{...l,[key]:val}:l)}))},updateQuestion=(i,key,val)=>{setReviewed(false);setForm(f=>({...f,quiz:f.quiz.map((q,j)=>j===i?{...q,[key]:val}:q)}))}
 const appendLesson=(lesson,title)=>{setReviewed(false);setForm(f=>({...f,title:f.title.trim()?f.title:title.slice(0,150),lessons:[...f.lessons.filter(l=>l.title.trim()&&l.body.trim()),lesson]}))}
 const appendQuiz=(question,title)=>{setReviewed(false);setForm(f=>({...f,title:f.title.trim()?f.title:title.slice(0,150),quiz:[...f.quiz.filter(q=>q.prompt.trim()),question]}))}
 const generateCode=()=>update('joinCode',Array.from(crypto.getRandomValues(new Uint8Array(12)),v=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[v%32]).join(''))
 async function parsePdf(e){setError('');const file=e.target.files?.[0];if(!file)return;setBusy(true);try{setRawText(await (file.name.toLowerCase().endsWith('.pdf')?extractPdf(file):file.text()));setNotice(`Extracted ${file.name} locally. Review the text and generate editable study suggestions.`)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function suggestions(ai=false){setBusy(true);setError('');try{const r=ai?await suggestWithFreeLocalAI(rawText):{data:deriveCourseNotes(rawText),method:'keyword extraction'};if(r.available===false){setNotice(r.reason);return}const notes=r.data;const lessons=notes.lessons?.filter(l=>l.title?.length>=2&&l.body?.length>=20).slice(0,20),quiz=notes.quiz?.filter(q=>q.prompt?.length>=4&&q.options?.length===4&&Number.isInteger(q.answerIndex)).slice(0,20);setForm(f=>({...f,summary:String(notes.summary||'').slice(0,800),lessons:lessons?.length?lessons:f.lessons,quiz:quiz?.length?quiz:f.quiz}));setNotice(`Generated editable drafts using ${r.method}. Check EVERY answer against your handout before saving. No file was uploaded.`)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function create(e){e.preventDefault();if(designerBusy)return;setBusy(true);setError('');setNotice('');try{const {joinCode,...content}=form;const result=await learningApi('/teacher/courses'+(editing?'/'+editing:''),{teacher:true,method:editing?'PUT':'POST',body:editing?content:form});setEditing(result.course.id);setSavedContent(JSON.stringify(content));setNotice(editing?'Private draft updated. Your course remains editable.':`Draft saved. Record this enrollment code securely: ${form.joinCode} — shown here only once. Continue editing here, or publish after reviewing every lesson and answer key.`);reload()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function openDraft(id){if(designerBusy||busy)return;setBusy(true);setError('');try{const r=await learningApi('/teacher/courses/'+id,{teacher:true});if(r.published)throw Error('This course is already published. Create a new draft to change it.');setForm({...r.course,joinCode:''});setSavedContent(JSON.stringify(r.course));setEditing(id);setReviewed(false);setNotice('Draft opened. Edit it and save your changes before publishing.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function publish(id){if(designerBusy||busy)return;try{await learningApi(`/teacher/courses/${id}/publish`,{teacher:true,method:'POST',body:{reviewed:true}});setNotice('Published. Give the enrollment code privately to your students.');if(editing===id){setEditing(null);setForm({...empty,lessons:[...empty.lessons],quiz:[{...empty.quiz[0],options:['','','','']}]});setReviewed(false)}reload()}catch(e){setError(e.message)}}
 async function showGrades(id){try{const d=await learningApi(`/teacher/courses/${id}/results`,{teacher:true});setResults(d);setSelected(id)}catch(e){setError(e.message)}}
 return <div className="mx-auto max-w-7xl space-y-8"><div><span className="chip"><Library size={14}/> Teacher-created courses</span><h1 className="mt-3 text-3xl font-bold">Learning studio</h1><p className="mt-2 max-w-3xl text-slate-400">Design a course with your PC AI or write it yourself. Generate lessons and quiz answers one item at a time, then review and publish. Only students who enter your private join code appear in your course report.</p></div>
 <div className="grid gap-6 xl:grid-cols-[1fr,340px]"><section className="glass p-6"><h2 className="flex gap-2 text-xl font-semibold"><BookPlus size={22} className="text-dps-neon"/> Create a course</h2><div className="mt-5 rounded-xl border border-dps-gold/20 bg-dps-gold/5 p-4"><h3 className="flex gap-2 font-semibold"><Sparkles size={18} className="text-dps-gold"/> Course source and handout assistant</h3><p className="mt-2 text-sm text-slate-300">Upload a text-based PDF or paste notes. The AI course designer sends selected text through the exam server to your configured PC model. Keyword extraction and optional browser AI remain available below.</p><input type="file" accept=".pdf,.txt,text/plain,application/pdf" className="mt-4 block w-full text-xs" disabled={busy||designerBusy} onChange={parsePdf} aria-label="Choose a PDF or text handout"/><textarea className="input mt-3 min-h-32" value={rawText} onChange={e=>setRawText(e.target.value)} disabled={busy||designerBusy} aria-label="Handout text" placeholder="Or paste a text handout here. Keep student-identifying information out of the document." maxLength={45000}/><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={()=>suggestions()} disabled={busy||designerBusy||rawText.length<150} className="btn btn-ghost btn-sm">Draft lessons + quiz</button><button type="button" onClick={()=>suggestions(true)} disabled={busy||designerBusy||rawText.length<150} className="btn btn-ghost btn-sm">Try free on-device AI</button></div><p className="mt-2 text-xs text-slate-500">Suggestions are not assessed or verified AI output. Always inspect answers before publishing.</p></div>
 <fieldset className="mt-5 flex flex-wrap gap-4 text-sm" disabled={busy||designerBusy}><legend className="label">Course designer mode</legend><label className="flex items-center gap-2"><input type="radio" name="course-designer-mode" checked={designer} onChange={()=>setDesigner(true)}/> AI course designer</label><label className="flex items-center gap-2"><input type="radio" name="course-designer-mode" checked={!designer} onChange={()=>setDesigner(false)}/> Manual course</label></fieldset>
 {designer&&<CourseAiDesigner examClass={form.className} language={form.language} sourceText={rawText} lessons={form.lessons} quiz={form.quiz} disabled={busy} onBusy={setDesignerBusy} onLesson={appendLesson} onQuiz={appendQuiz}/>}
 {storageError&&<p role="alert" className="mt-3 text-sm text-amber-300">This browser could not keep a local copy. Save a private draft before leaving.</p>}
 <form className="mt-6 space-y-5" onSubmit={create}><fieldset disabled={busy||designerBusy} className="space-y-5"><legend className="sr-only">Editable course</legend><div className="grid gap-4 md:grid-cols-2"><label className="block text-sm">Course title<input className="input mt-1" required maxLength={150} minLength={4} value={form.title} onChange={e=>update('title',e.target.value)} placeholder="Python loops and logic"/></label><label className="block text-sm">Subject / language<select className="input mt-1" value={form.language} onChange={e=>update('language',e.target.value)}>{['python','web','java','c','cpp','sql','blocks'].map(x=><option key={x} value={x}>{x.toUpperCase()}</option>)}</select></label><label className="block text-sm">Class<select className="input mt-1" value={form.className} onChange={e=>update('className',e.target.value)}>{['VI','VII','VIII','IX','X','XI','XII'].map(x=><option key={x}>{x}</option>)}</select></label><label className="block text-sm">Private enrollment code<span className="flex gap-2"><input className="input mt-1" minLength={10} maxLength={40} type="text" required={!editing} disabled={!!editing} placeholder={editing?'Existing code kept':'Generate a private code'} value={form.joinCode} onChange={e=>update('joinCode',e.target.value)}/><button type="button" className="btn btn-ghost btn-sm mt-1" onClick={generateCode} disabled={!!editing}>Generate</button></span></label></div><label className="block text-sm">Summary<textarea className="input mt-1" rows={3} value={form.summary} maxLength={800} onChange={e=>update('summary',e.target.value)}/></label>
 <div className="border-t border-white/10 pt-5"><h3 className="font-semibold">Lessons ({form.lessons.length})</h3>{form.lessons.map((l,i)=><div className="mt-3 space-y-2 rounded-xl border border-white/10 p-4" key={i}><input required minLength={2} className="input" aria-label={`Lesson ${i+1} title`} placeholder={`Lesson ${i+1} title`} value={l.title} onChange={e=>updateLesson(i,'title',e.target.value)}/><textarea required minLength={20} maxLength={12000} rows={5} className="input" aria-label={`Lesson ${i+1} content`} placeholder="Explain the topic, with examples..." value={l.body} onChange={e=>updateLesson(i,'body',e.target.value)}/><button type="button" className="btn btn-ghost btn-sm" onClick={()=>{setReviewed(false);setForm(f=>({...f,lessons:f.lessons.filter((_,j)=>j!==i)}))}}>Delete lesson {i+1}</button></div>)}<button type="button" className="btn btn-ghost btn-sm mt-3" onClick={()=>setForm(f=>({...f,lessons:[...f.lessons,{title:`Lesson ${f.lessons.length+1}`,body:''}]}))}>Add lesson</button></div>
 <div className="border-t border-white/10 pt-5"><h3 className="font-semibold">End-of-course questions ({form.quiz.length})</h3>{form.quiz.map((q,i)=><div className="mt-3 space-y-2 rounded-xl border border-white/10 p-4" key={i}><input className="input" minLength={4} required aria-label={`Question ${i+1} prompt`} placeholder={`Question ${i+1}`} value={q.prompt} onChange={e=>updateQuestion(i,'prompt',e.target.value)}/><div className="grid gap-2 sm:grid-cols-2">{q.options.map((v,j)=><input className="input" key={j} value={v} minLength={1} maxLength={180} required aria-label={`Question ${i+1}, option ${j+1}`} placeholder={`Option ${j+1}`} onChange={e=>updateQuestion(i,'options',q.options.map((old,k)=>k===j?e.target.value:old))}/>)}</div><label className="block text-xs text-slate-400">Verified correct answer<select className="input mt-1" value={q.answerIndex} onChange={e=>updateQuestion(i,'answerIndex',Number(e.target.value))}>{q.options.map((_,k)=><option key={k} value={k}>Option {k+1}</option>)}</select></label><button type="button" className="btn btn-ghost btn-sm" onClick={()=>{setReviewed(false);setForm(f=>({...f,quiz:f.quiz.filter((_,j)=>j!==i)}))}}>Delete course question {i+1}</button></div>)}<button type="button" className="btn btn-ghost btn-sm mt-3"  onClick={()=>setForm(f=>({...f,quiz:[...f.quiz,{prompt:'',options:['','','',''],answerIndex:0}]}))}>Add question</button></div>
 <div className="border-t border-white/10 pt-5"><h3 className="font-semibold">Resource links</h3><p className="mb-3 text-xs text-slate-400">Link to approved HTTPS PDFs, reference websites or private handouts. File uploads require separate private storage.</p>{form.resources.map((r,i)=><div key={i} className="mb-3 grid gap-2 sm:grid-cols-2"><input className="input" aria-label={`Resource ${i+1} title`} placeholder="Resource title" value={r.title} onChange={e=>setForm(f=>({...f,resources:f.resources.map((x,j)=>j===i?{...x,title:e.target.value}:x)}))}/><input className="input" type="url" aria-label={`Resource ${i+1} URL`} placeholder="https://..." value={r.url} onChange={e=>setForm(f=>({...f,resources:f.resources.map((x,j)=>j===i?{...x,url:e.target.value}:x)}))}/></div>)}<button type="button" className="btn btn-ghost btn-sm" onClick={()=>setForm(f=>({...f,resources:[...f.resources,{title:'',url:''}]}))} disabled={form.resources.length>=8}>Add resource</button></div>
 {error&&<p role="alert" className="text-sm text-red-300">{error}</p>}{notice&&<p role="status" className="rounded-xl border border-dps-green/20 bg-emerald-500/10 p-4 text-sm text-dps-neon">{notice}</p>}<button className="btn btn-primary" disabled={busy}>{busy?<Loader2 size={16} className="animate-spin"/>:<FileText size={16}/>} {editing?'Update private draft':'Save private draft'}</button>
 {editing&&<label className="flex items-start gap-2 text-sm"><input type="checkbox" disabled={savedContent!==currentContent} checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> I checked every lesson and course answer key, and saved my changes.</label>}
 {editing&&<button type="button" className="btn btn-primary" disabled={!reviewed||savedContent!==currentContent} onClick={()=>publish(editing)}>Publish reviewed course</button>}</fieldset></form></section>
 <aside className="space-y-5"><section className="glass p-5"><h2 className="font-semibold">Your courses</h2><p className="mt-1 text-xs text-slate-500">Drafts are private until you publish them.</p>{loading?<Spinner label="Loading your courses…"/>:courses.length===0?<p className="mt-4 text-sm text-slate-400">No courses yet.</p>:courses.map(c=><article className="mt-4 rounded-xl border border-white/10 p-4" key={c.id}><span className="chip">{c.published?'Published':'Draft'}</span><h3 className="mt-2 font-semibold">{c.title}</h3><p className="mt-1 text-xs text-slate-400">Class {c.className} • {c.lessonCount} lessons</p><div className="mt-4 flex flex-wrap gap-2">{!c.published&&<button className="btn btn-primary btn-sm" disabled={busy||designerBusy} onClick={()=>openDraft(c.id)}>Continue draft</button>}<button className="btn btn-ghost btn-sm" onClick={()=>showGrades(c.id)}>Student scores</button></div></article>)}</section>{results&&<section className="glass p-5"><h3 className="font-semibold">Course results</h3><p className="mt-2 text-xs text-slate-400">Only enrolled nicknames; not official school marks.</p>{results.students.length===0?<p className="mt-4 text-sm text-slate-400">No students joined yet.</p>:results.students.map((s,i)=><div key={i} className="mt-3 flex flex-col gap-1 border-b border-white/5 pb-3 text-sm"><b>{s.handle}</b><span className="text-slate-400">Class {s.class_name} • {s.completed_lessons.length} lessons • Best {s.best_score??'—'}%</span></div>)}</section>}</aside></div></div>
}
